equistore/_c_api.py
equistore/tensor.py
include/equistore.h
src/c_api/tensor.rs
src/data.rs
src/tensor/keys_to_properties.rs
src/tensor/keys_to_samples.rs
src/tensor/mod.rs
src/tensor/utils.rs

`keys_to_properties` can now takes as input a set of `Labels` containing the values the user wants to move from keys to properties. The intended use case is to be able to create a "species dense" representation of a frame with a pre-determined set of species, for example predicting AlO3 on a model trained on Al-Si-O dataset. Ideally we would want to do the prediction with (neighbor) species-sparse descriptor, but (neighbor) species dense representation is good enough and much easier to work with.
The previous behavior ("just take whatever is in the keys & use is in properties") is still available by passing an empty set of Labels (or in Python a list of strings).
This is similar to `"expansion_by_species_method": "user defined", "global_species": [1, 5, 6, 33]` in librascal.

Allow to provide values for the keys in keys_to_properties

---

equistore/block.py
equistore/labels.py
equistore/tensor.py
tests/python/blocks.py
tests/python/tensor.py
tests/python/utils.py

In the spirit of issue #32. I added an idea for two `__repr__` functions for TensorMap and TensorBlock.
In TensorMap it basically prints the keys and its names:
```
>> Tensor
TensorMap 
keys: [(0, 1, 1), (0, 1, 6), (0, 1, 8), (0, 6, 1), (0, 6, 6), (0, 6, 8), (0, 8, 1), (0, 8, 6), (0, 8, 8)]
key_names: ['spherical_harmonics_l', 'species_center', 'species_neighbor']
```
For the TensorBock, the function prints the names of the samples, components and properties:
```
>> Tensor.block(0)
TensorBlock 
samples: ['structure', 'center']
component: ['spherical_harmonics_m']
properties: ['n']
```
The example are taken from a spherical harmonic expansion Tensor.

Added first attempt of __repr__ for TensorMap and TensorBlock

---

include/equistore.hpp
tests/cpp/labels.cpp

memcmp work with bytes, and was only comparing the first few bytes of the data

Fix operator== for NDArray<T>

---

equistore/_c_lib.py
equistore/block.py
equistore/data/__init__.py
equistore/data/array.py
equistore/data/extract.py
equistore/io.py
equistore/status.py
include/equistore.hpp
tests/python/data.py

The goal is to expose C++ `torch::Tensor` as Python `torch.Tensor` if possible

Enable external Python packages to register new array wrappers

---

equistore/tensor.py
tests/python/tensor.py

-- added a few checks in the length of `args` before `tensor.block(0,5)==tensor.block(0)`, because it checked only that the first argument was an `int` and then returned the result. Now the code raises an error:
`raise ValueError(
f"only one non-keyword argument is supported, {len(args)} are given"
)`
This behaviour was actually true only if the first positional argument was an `int` because a similar check was done by the `blocks_matching` function, which was not called if `args[0]` was `int`. I also left the check inside `blocks_matching` even though now it is probably never called.
-- added the `__getitem__()` function to `TensorMap`.
Now, `tensor[0]` gives the same result of `tensor.block(0)`
it works also for keys: `tensor[tensor.keys[0]]` is equivalent to …

added __getitem()__ and added a check for multiple positional arguments in tensor.block and tensor.blocks

---

.github/workflows/comment-wheels-pr.yml
.github/workflows/docs.yml
.readthedocs.yml

Same as in [rascaline](https://github.com/Luthaf/rascaline/pull/102), this PR adds the necessary config for a Readthedocs (RTD) workflow. With RTD the docs are build for every PR and can be inspected without checking out the code locally..

Added workflow for ReadTheDocs

---

equistore/data/extract.py
tests/python/data.py
tests/python/serialization.py

Stop keeping reference to TensorBlock in freshly allocated array

---

src/labels.rs
src/tensor/mod.rs

Follow up to #60, for consistency in the methods naming

Rename TensorMap::block_mut to TensorMap::block_mut_by_id

---

python/tests/data/README.md

The data files used for unit tests:
- qm7-power-spectrum.npz
- qm7-spherical-expansion.npz
were reported in the rascaline hypers in the README to have no gradients calculated, but in fact have both 'cell' and 'positions' gradients calculated.
These hypers will also need updating to reflect the new format used in Rascaline, but this will be raised in another issue.
Closes #76

Editing error in rascaline hypers (gradients)

---

python/src/equistore/data/array.py

When writing a `TensorMap` to file, where the `TensorBlock.values` tensors are of type `torch.tensor`, the `equistore.io.save` function fails with a `ValueError`.
```python
ValueError                                Traceback (most recent call last)
File /opt/miniforge3/envs/qml/lib/python3.10/site-packages/equistore/utils.py:31, in catch_exceptions.<locals>.inner(*args, **kwargs)
30 try:
---> 31     function(*args, **kwargs)
32 except Exception as e:
File /opt/miniforge3/envs/qml/lib/python3.10/site-packages/equistore/data/array.py:118, in _eqs_array_data(this, data)
117 if array.device.type == "cpu":
--> 118     raise ValueError("can not get data pointer for tensors not on CPU")
120 # `.numpy()` will fail if the data is on GPU or requires gradient
121 # tracking, and the resulting array …
```

Fix bug in io.save of torch-based tensormaps

---

docs/src/reference/python/operations/index.rst
docs/src/reference/python/operations/slice.rst
python/src/equistore/operations/__init__.py
python/src/equistore/operations/slice.py
python/tests/operations/slice.py

**Overview**
Functions to slice equistore tensors based on some specified samples, properties, or both. All functions are documented, and there is a suite of associated unit tests.
This pull request supersedes that of PR #37. These slice functions have been implemented as a helper module in the `operations/` subdirectory as opposed to as a class method in `tensor.py`. 
**Functionality**
In `slice.py`, there are 3 new functions. All are documented and have unit tests.
**1. `_slice_tensorblock(tensorblock, samples_to_slice=None, properties_to_slice=None)`**
* This slices an individual `TensorBlock`, including gradients, according to the arguments `samples_to_slice` and `properties_to_slice`. It returns a new `TensorBlock`, where the shape of the values tensor (`TensorBlock.values`) is …

Tensor slice functions and unit tests

---

python/src/equistore/operations/slice.py
python/tests/operations/slice.py

The issue was that the new gradient samples where just picked out of the old ones, but they need to be updated to refer to the new samples. For example, a block with gradient samples `[0, 1, 1, 2, 2, 3]` where samples 1 and 3 where picked need to be updated to read `[0, 0, 1]`. This only applies to the first column (`name = "sample"`) of the  gradient samples.

Cleanup tests and fix a bug for slice operation

---

python/src/equistore/operations/slice.py
python/tests/operations/slice.py

Minor changes to docs:
1. Add return type to the ``slice`` function
2. Change erroneous arg names ``samples`` and ``properties`` in docstring code examples of ``slice`` and ``slice_block`` fxns to ``samples_to_slice`` and ``properties_to_slice``.

Fix incorrect code example in docs

---

.github/workflows/tests.yml

As discussed in #88 before we move to more modern package/build infrastructure we have to test that this still works on all supported versions. This PR adds a matrix to the build test ranging from Python 3.6 up to 3.11.

Added more Python versions to the build test

---

include/equistore.h
include/equistore.hpp
python/scripts/generate-declarations.py
python/src/equistore/_c_api.py
python/src/equistore/block.py
python/src/equistore/data/__init__.py
python/src/equistore/data/array.py
python/src/equistore/data/extract.py
python/src/equistore/tensor.py
python/tests/data.py
python/tests/tensor.py
src/c_api/tensor.rs
src/tensor/keys_to_properties.rs
src/tensor/keys_to_samples.rs
src/tensor/mod.rs
tests/cpp/tensor.cpp

The first commit is extracted from #85, and required to make the second one work.
The second commit fixes #58 and is a API breaking change. It will make #85 easier to implement in full.
```py
tensor = ...
tensor.keys_to_properties("species_neighbor")
tensor = ...
tensor = tensor.keys_to_properties("species_neighbor")
```
TODO before merging:

Make Tensormap immutable

---

python/src/equistore/block.py
python/src/equistore/operations/reduce_over_samples.py
python/tests/blocks.py

following @ceriottm suggestion, now the print fuction prints also the shapes of the different direction of the tensorblock, basically the block.value.shape .
This first commit is a draft ( do not pass the test becouse i haven't modified them).
i think that there are different possible ways to show the shapes. The codes I have here does that:
```
>> tensor[1]
TensorBlock
samples (len: 52): ['structure', 'center']
components (len: [3]): ['spherical_harmonics_m']
properties (len: 4): ['n']
gradients: ['cell', 'positions']
>>tensor[1].gradient('positions')
Gradient TensorBlock 
parameter: 'positions'
samples (len: 128): ['sample', 'structure', 'atom']
components (len: [3, 3]): ['direction', 'spherical_harmonics_m']
properties (len: 4): ['n']
```
Now at each different dimension (sample, …

added the printing of shapes in the print function

---

docs/src/reference/python/operations/index.rst
docs/src/reference/python/operations/join.rst
python/src/equistore/operations/__init__.py
python/src/equistore/operations/_dispatch.py
python/src/equistore/operations/_utils.py
python/src/equistore/operations/allclose.py
python/src/equistore/operations/join.py
python/src/equistore/operations/lstsq.py
python/src/equistore/operations/solve.py
python/tests/operations/join.py
src/blocks.rs

Closes #62
This PR adds two new operations. First `join_along_samples` similar to `vstack`  and second `join_along_properties` similar to `hstack`.

Add join functions

---

python/src/equistore/operations/join.py
python/tests/operations/join.py

When try to join labels of different number of names like
```python
property_labels_1 = Labels(
("structure", "prop_1"), np.vstack(2 * [np.arange(5)]).T
)
property_labels_2 = Labels(
("structure", "prop_2", "prop_3"), np.vstack(3 * [np.arange(5)]).T
)
```
the `_join_labels` label function raises an error because `np.unique` doesn't work with arrays of inhomogeneous shape. This issue is fixed in this PR.

Fix joining labels with different number of names

---

.github/workflows/build-wheels.yml
.github/workflows/comment-wheels-pr.yml
.github/workflows/docs.yml
.github/workflows/tests.yml
.readthedocs.yml
CONTRIBUTING.rst
python/scripts/build-wheels/Dockerfile
python/src/equistore/operations/join.py
python/src/equistore/operations/slice.py

This PRs updates a number of dependencies to allow building the equistore.
1. All Github actions are upgraded to the latest version
2. Use glibc with version 2.28 of the python wheels. Required by rustup
3. Update the mininal rust version to 1.59. Required by zip.

Use glibc==2.28 and rust==1.59

---

python/src/equistore/operations/_utils.py

As @curiosity54 found out: The `_check_blocks` function is not testing correctly for components of two blocks. Since components are of type `List[Labels]` a simple comparison with `==`  is not suitable. Here, `_check_blocks` is extended to test for the length and for the equality using the same code as for gradients.

Check components in a propper way

---

python/src/equistore/io.py
python/src/equistore/operations/lstsq.py
python/src/equistore/operations/slice.py

This PR explicitly sets the `stacklevel` of warnings since this is required by [flake8](https://github.com/PyCQA/flake8-bugbear):
> B028: No explicit stacklevel keyword argument found. The warn method from the warnings module uses a stacklevel of 1 by default. This will only show a stack trace for the line on which the warn method is called. It is therefore recommended to use a stacklevel of 2 or greater to provide more information to the user.
Here, I set the level to `stacklevel=1` (the default) meaning that no additional backtrace information is given. I think we do not need more information for the user because the warnings are well written and a link and codeblock does not help much. If you disagree we can also set it to `2` or `3`.

Please B028 linting error

---

docs/src/reference/python/operations/logic/equal.rst
docs/src/reference/python/operations/logic/index.rst
python/src/equistore/operations/__init__.py
python/src/equistore/operations/_dispatch.py
python/src/equistore/operations/_utils.py
python/src/equistore/operations/add.py
python/src/equistore/operations/allclose.py
python/src/equistore/operations/divide.py
python/src/equistore/operations/equal.py
python/src/equistore/operations/join.py
python/src/equistore/operations/lstsq.py
python/src/equistore/operations/multiply.py
python/src/equistore/operations/solve.py
python/tests/operations/allclose.py
python/tests/operations/equal.py
python/tests/operations/join.py

In the spirit of #119  I rewrote them in a more stringent way and allclose now use them to do all the checks for the metadata . This implies that all the test of allclose now are on these functions. I think everything has a test (maybe not all the gradient possibilities).
What do you think? 
I, of course, can create the equal functions, being the same as allclose except for the more stringent numerical checks, but I do not know if it really usefull.

rewrite of _utils._check_blocks _utils._check_same_gradients,

---

docs/src/reference/python/operations/manipulation/index.rst
docs/src/reference/python/operations/manipulation/split.rst
python/src/equistore/operations/__init__.py
python/src/equistore/operations/_utils.py
python/src/equistore/operations/slice.py
python/src/equistore/operations/split.py
python/tests/operations/slice.py
python/tests/operations/split.py

**1. Split**
This PR introduces the ``split`` and ``split_block`` functions, which are essentially wrappers for the private function ``_slice_block`` found in operations/slice.py. They allow tensors (TensorMap or TensorBlock, respectively) to be split into multiple tensors according to a specified index name along either the "samples" or "properties" axis, and returned in a list.
How they work:
```py
import numpy as np
from equistore import io, Labels
from equistore.operations import split
tensor = io.load("path/to/tensor.npz")
split_tensor = split(
tensor,
axis="samples",
grouped_idxs=[
Labels(
names=["structure"],
values=np.array([[0], [6], [7]])
),
Labels(
names=["structure"],
values=np.array([[2], [3], [4]])
),
Labels(
names=["structure"],
values=np.array([[1], [5], [8], [9], [10]]) …
```

Split function and more numpy-esque slice

---

docs/src/reference/python/operations/index.rst
docs/src/reference/python/operations/set/index.rst
docs/src/reference/python/operations/set/unique_metadata.rst
python/src/equistore/operations/__init__.py
python/src/equistore/operations/unique_metadata.py
python/tests/operations/unique_metadata.py

Re-do of PR #117, will close branch 'unique'. This PR introduces the operations ``unique_metadata`` and ``unique_metadata_block`` with a more descriptive name than in PR #117 and while staying inside ``equistore.operations``, with documentation living inside the 'operations/set' sub-class of operations.
**Usage**
To find the unique structure indices of the samples metadata of the blocks of a TensorMap:
```py
from equistore import io
from equistore.operations import unique_metadata
tensor = io.load("/path/to/tensor.npz")
unique_structures = unique_metadata(tensor, axis="samples", names=["structure"])
unique_structures
>>> Labels([(0,), (1,), (2,), (3,), (4,), (5,), (6,), (7,), (8,), (9,)], dtype=[('structure', '<i4')])
```
For the gradient blocks to find, for instance, the samples named …

New operation ``unique_metadata``

---

.github/workflows/tests.yml
CONTRIBUTING.rst
Cargo.toml

Bumps the version of rustc to 1.61. Now, we have a consistent 1.61 version everywhere: in the tests, the rtd script and also in the Cargo.toml.

Bump minimal rustc version to 1.61

---

.github/workflows/docs.yml

Read the docs [offers a GH new action](https://github.com/readthedocs/actions/tree/v1/preview) to post the link to the docs. This simplifies our workflow a bit.
----
:books: Documentation preview :books:: https://equistore--136.org.readthedocs.build/en/136/

Use ReadtheDocs action for posting link to PR docs

---

.github/workflows/docs.yml

The RTD post fails if it is not on a PR...
----
:books: Documentation preview :books:: https://equistore--138.org.readthedocs.build/en/138/

Fix RTD post only running on PRs

---

CODE_OF_CONDUCT.rst
CONTRIBUTING.rst

Fixes #132 
I also moved the code of conduct to a different file. [It should then be linked in the sidebar on Github.](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)
----
:books: Documentation preview :books:: https://equistore--139.org.readthedocs.build/en/139/

Add explanation on Python docstring format

---

python/src/equistore/labels.py
python/tests/labels.py

If an empty array is given to the constructor of a `Labels` instance it is now automatically converted into the correct shape. This allows inputs like
```python
Labels(["sample", "structure", "atom"], np.array([]))
```
without manually reshaping as required before
```python
Labels(["sample", "structure", "atom"], np.zeros([0, 3], dtype=np.int32))
```
Also, a function Labels.empty() is added, allowing even simpler constructions like 
```python
Labels.empty(["sample", "structure", "atom"])
```
----
:books: Documentation preview :books:: https://equistore--160.org.readthedocs.build/en/160/

Convenience functions for Labels

---

.github/workflows/docs.yml

This seems to be required to post messages on PR opened from a fork
----
:books: Documentation preview :books:: https://equistore--163.org.readthedocs.build/en/163/

Add write permission to the doc builder on CI

---

pyproject.toml
python/tests/blocks.py
python/tests/data.py
python/tests/labels.py
python/tests/operations/unique_metadata.py
python/tests/serialization.py
python/tests/tensor.py
python/tests/utils.py
tox.ini

This PR moves the Python core tests to `pytest`. The operations tests still use `unittests`. In addition, I added torch in test depencies for also running the data tests for torch. 
----
:books: Documentation preview :books:: https://equistore--165.org.readthedocs.build/en/165/

Port Python core tests to pytest

---

.github/workflows/docs.yml
.github/workflows/documentation-links.yml

The job pushing documentation to gh-pages is broken right now (https://github.com/lab-cosmo/equistore/actions/runs/4341978102/jobs/7582234507), I suspect this is because of the tentative permission fix from #163. This PR tries to workaroud the issue in another way, having a separate workflow for posting the link

Try to fix docs permission errors

---

equistore-core/src/blocks.rs
python/tests/blocks.py

This should fix the `internal error (this is likely a bug, please report it): index out of bounds: the len is 0 but the index is 0` when trying to add gradient with completely empty samples:
```py
block.add_gradient(
"parameter",
data=np.zeros((0, 2)),
samples=Labels([], np.empty((0, 2), dtype=np.int32)),
components=[],
)
```
----
:books: Documentation preview :books:: https://equistore--169.org.readthedocs.build/en/169/

Check that we have at least one dimension in gradient samples

---

python/src/equistore/block.py
python/tests/blocks.py

fixes the last issue of #129.
now 
```python
block = TensorBlock(
values=np.zeros((0, 2)),
samples=Labels([], np.empty((0, 2), dtype=np.int32)),
components=[],
properties=Labels(["properties"], np.array([[5], [3]], dtype=np.int32)),
)
```
gives 
```python
TensorBlock
samples (0): []
components (): []
properties (2): ['properties']
gradients: no
```
----
:books: Documentation preview :books:: https://equistore--166.org.readthedocs.build/en/166/

print can handle 0 samples

---

tox.ini

Otherwise we would just add new files in the package without removing previous ones. This was causing @jwa7 to see tests passing locally while failing in CI in #178 
----
:books: Documentation preview :books:: https://equistore--180.org.readthedocs.build/en/180/

Make sure to uninstall existing python package in tox

---

python/src/equistore/labels.py
python/tests/labels.py

Fix #188 
----
:books: Documentation preview :books:: https://equistore--189.org.readthedocs.build/en/189/

Make Labels contiguous before passing them to equistore-core

---

.readthedocs.yml
docs/src/conf.py
python/scripts/build-wheels/Dockerfile

fixing #171
----
:books: Documentation preview :books:: https://equistore--184.org.readthedocs.build/en/184/

Added viewcode extension to sphinx to view source code in documentation [fixing #171]

---

python/src/equistore/operations/join.py
python/tests/operations/join.py

Very useful, for example, when batching calculations for memory reasons and joining the batches in the end. In that case, if there is only one batch, the join operation will not currently work
----
:books: Documentation preview :books:: https://equistore--220.org.readthedocs.build/en/220/

Allow join for a single TensorMap

---

equistore-core/CMakeLists.txt
equistore-core/cmake/equistore-config.in.cmake
setup.py

And only install the shared one for Python wheels. The wheel goes from ~7MiB to ~500kiB for me with this change.
----
:books: Documentation preview :books:: https://equistore--181.org.readthedocs.build/en/181/

Allow to only install one of static/shared library

---

python/tests/operations/join.py

As a starting point to address #195 and #203 this PR ports the tests of `join` to pytest.
----
:books: Documentation preview :books:: https://equistore--221.org.readthedocs.build/en/221/

Port join tests to pytest

---

python/src/equistore/operations/_dispatch.py
python/src/equistore/operations/divide.py
python/src/equistore/operations/join.py
python/src/equistore/operations/lstsq.py
python/src/equistore/operations/multiply.py
python/src/equistore/operations/pow.py
python/src/equistore/operations/solve.py

numpy vstack, hstack, and dstack operations essentially wrap a `concatenate` operation along axes 0, 1, and 2, respectively. For TensorMaps with multiple components dimensions this nomenclature can be confusing. 
This PR removes explicit calls to `_dispatch.xstack`, replacing them with `_dispatch.concatenate`, requiring the axis to be passed by hand. This should help avoid bugs in the future, such as in #195.
----
:books: Documentation preview :books:: https://equistore--224.org.readthedocs.build/en/224/

Convert `stack` dispatch operations to `concatenate`

---

python/src/equistore/operations/join.py
python/tests/operations/join.py

Fixes #195 and #159
Instead of reimplementing everything from scratch `join` now uses the `keys_to_properties` or `keys_to_samples` methods for joining a list of TensorMaps. This does solve the two issues, simplifies the code and leads to a 7-8 times speedup compared to the current master branch:
```python
tensor = equistore.load(
os.path.join("../python/tests/data/qm7-power-spectrum.npz"), use_numpy=True
)
%timeit join([tensor,tensor], axis="properties")
```
`5.03 ms ± 82.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)`
```python
%timeit equistore.join([tensor,tensor], axis="properties")
```
`37.1 ms ± 336 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)`
The only drawback is that we now have a `tensor` label after the joining. I think this is acceptable for now. I …

Use `keys_to_x` for join operation

---

docs/requirements.txt
docs/src/conf.py

The `toggleprompt` adds a button on the upper left of each example block to remove the `>>>` inputs. This is very useful when copying more complex examples.
----
:books: Documentation preview :books:: https://equistore--234.org.readthedocs.build/en/234/

Add toggleprompt button to html docs

---

python/tests/blocks.py
python/tests/labels.py
python/tests/operations/add.py
python/tests/tensor.py

As given in the title the tests for the `add` operation is ported to pytest. I, also did some changed to how we provide the strings to the `match`  parameter. I think it is a bit easier to read now.
----
:books: Documentation preview :books:: https://equistore--170.org.readthedocs.build/en/170/

Port `add` function tests to pytest

---

.github/workflows/tests.yml
CONTRIBUTING.rst
equistore-core/tests/cpp/CMakeLists.txt
setup.py

We do this in rascaline and I was persuaded we already did it here as well.
TODO: 
----
:books: Documentation preview :books:: https://equistore--236.org.readthedocs.build/en/236/

Add a test checking the C API with valgrind

---

python/src/equistore/block.py
python/src/equistore/tensor.py
python/tests/blocks.py
python/tests/tensor.py

They will result in double free, since two Python objects now refer to the same C pointer.
This fixes the issue in https://github.com/lab-cosmo/equistore/issues/134#issuecomment-1477760811 by making this test raise an exception instead of trying to double free the pointer.
This should only impact people trying to use `copy.copy` to make copies, instead of `TensorMap.copy` or `copy.deepcopy`.
----
:books: Documentation preview :books:: https://equistore--226.org.readthedocs.build/en/226/

Disable shallow copies of TensorMap/TensorBlock

---

.github/workflows/tests.yml
CONTRIBUTING.rst
MANIFEST.in
setup.cfg
setup.py
tox.ini

Also add a way to only run a subset of tests and document it.
This PR is nice to have on master, but will help quite a lot for #233, where we need an environment with a fresh build of both equistore and equistore_torch
----
:books: Documentation preview :books:: https://equistore--237.org.readthedocs.build/en/237/

Use tox external package support to only build the wheels only once

---

equistore-core/Cargo.toml
equistore-core/src/io/labels.rs
equistore-core/src/io/mod.rs
equistore-core/src/io/npy_header.rs

These are used to implement the npz reader/writer for `equistore::io::save`/`equistore::io::load`, but are relatively heavy dependencies for what we do with them. Removing them shaves 20% out of equistore compile time.
Instead of the dependency, the code now uses a small handwritten parser for the couple of Python literals we need to read instead of a generated [pest](https://docs.rs/pest/latest/pest/) parser.
---
I had this branch sitting on my computer for a while, it might be time to merge it =)
----
:books: Documentation preview :books:: https://equistore--240.org.readthedocs.build/en/240/

Remove dependency on py-litteral and pest

---

python/src/equistore/operations/drop_blocks.py
python/tests/operations/drop_blocks.py
python/tests/operations/equal_metadata.py

This flag dictates whether or not the underlying data of the input TensorBlocks (and Gradients) should be copied for the returned TensorMap.
Setting to False, the the new TensorMap is constructed with a reference to the original data. This of course could be unsafe if the user manipulates via one reference and unknowingly changes the other. However, the advantage for the careful user is that a large increase in memory usage is not created.
Default value is set to False.
Also done in this PR (and not in a separate one, for no good reason) was a removal of the test class in the test script unique_metadata.py
----
:books: Documentation preview :books:: https://equistore--248.org.readthedocs.build/en/248/

`drop_blocks()` - add a `copy` flag

---

equistore-core/src/io/npy_header.rs

Fixes https://github.com/lab-cosmo/equistore/pull/238#issuecomment-1498040918
This is a follow up to #240, which broke reading files we just wrote

Skip whitespaces after opening { in npy header

---

python/src/equistore/block.py
python/src/equistore/io.py
python/src/equistore/tensor.py
python/tests/serialization.py

First draft of pickling by converting everything to numpy arrays. Creates additional copies for conversion to numpy array, but when numpy arrays and pickle protocol 5 is used, no spurious copies should be made for the values. Need to check this. Also current test only works, because it only handles numpy arrays. I am sure with torch tensor it will fail (gradients are not converted)
----
:books: Documentation preview :books:: https://equistore--238.org.readthedocs.build/en/238/

Pickling support by converting to numpy

---

python/scripts/convert-equistore-npz.py

This is a follow-up to #253. I used `savez_compressed` there to update the tests data, but this should not be the default since equistore-core does not know how to read such files.
----
:books: Documentation preview :books:: https://equistore--259.org.readthedocs.build/en/259/

When converting between npz formats, save files uncompressed

---

equistore-core/CMakeLists.txt
equistore-core/tests/cpp/CMakeLists.txt

We need to declare that cargo-build-equistore is the command to use to create static/shared equistore library, or ninja gets confused.
----
:books: Documentation preview :books:: https://equistore--260.org.readthedocs.build/en/260/

Fix CMakeLists.txt for Ninja generator

---

.github/workflows/rust-tests.yml
equistore-core/CMakeLists.txt
equistore-core/cmake/equistore-config.in.cmake
equistore-core/tests/cmake-project/CMakeLists.txt
equistore-core/tests/cpp/CMakeLists.txt
equistore-core/tests/cpp/external/CMakeLists.txt

This is the default for Ubuntu 20.04, and it is relatively easy to get a newer version if someone needs it on a different system.
----
:books: Documentation preview :books:: https://equistore--267.org.readthedocs.build/en/267/

Upgrade minimal CMake version to 3.16

---

python/equistore-operations/equistore/operations/_dispatch.py
python/equistore-operations/tests/dispatch.py

dim=None results in an error, because torch uses a different function when dim is not given.
I would like to add a test, but it seems like one has to to adapt the tests that they also run for torch arrays and that is a bit too much for me now.
----
:books: Documentation preview :books:: https://equistore--269.org.readthedocs.build/en/269/

Fix all function for torch array when axis is None

---

README.rst

The previous badge was pointing to the tests workflow, which no longer exist 
----
:books: Documentation preview :books:: https://equistore--272.org.readthedocs.build/en/272/

Use commit status badge instead of a specific workflow

---

python/equistore-core/setup.py
python/equistore-core/version_from_git.py
python/equistore-operations/setup.py
python/equistore-operations/version_from_git.py

Full repo archive contains raw symlink (similar to windows) which we need to handle when reading `AUTHORS` / `version_from_git`
----
:books: Documentation preview :books:: https://equistore--273.org.readthedocs.build/en/273/

Re-enable building from a full repo archive

---

equistore-core/Cargo.toml
equistore-core/include/equistore.h

This work around https://github.com/mozilla/cbindgen/issues/841
----
:books: Documentation preview :books:: https://equistore--277.org.readthedocs.build/en/277/

Pin cbindgen to v0.24.5

---

python/equistore-operations/setup.py
setup.py

`~=` means "not this version"
----
:books: Documentation preview :books:: https://equistore--279.org.readthedocs.build/en/279/

Fix version specification for Python packages

---

.github/workflows/build-wheels.yml
equistore-core/src/c_api/blocks.rs
equistore-core/src/c_api/labels.rs
equistore-core/src/c_api/tensor.rs
equistore-core/src/data.rs
equistore/src/block/block_ref.rs
equistore/src/data/array.rs
equistore/src/data/array_ref.rs
equistore/src/io.rs
equistore/src/labels.rs

Extracted from #263. 
This function can not be called with a null pointer, even if the length of the slice is zero, cf https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html.
So in cases where the C API allow the pointer to be null when the length is zero, we manually create an empty slice.
----
:books: Documentation preview :books:: https://equistore--276.org.readthedocs.build/en/276/

Do not call std::slice::from_raw_parts with null pointer

---

docs/src/reference/c/block.rst
docs/src/reference/c/labels.rst
docs/src/reference/c/tensor.rst
equistore-core/Cargo.toml
equistore-core/include/equistore.h
equistore-core/include/equistore.hpp
equistore-core/src/c_api/labels.rs
equistore-core/src/labels.rs
equistore-core/tests/cpp/labels.cpp
equistore-torch/include/equistore/torch/labels.hpp
equistore-torch/src/labels.cpp
equistore-torch/src/register.cpp
equistore-torch/tests/labels.cpp
equistore/src/c_api.rs
equistore/src/labels.rs
python/equistore-core/equistore/core/_c_api.py
python/equistore-core/equistore/core/labels.py
python/equistore-core/tests/labels.py
python/equistore-operations/equistore/operations/drop_blocks.py
python/equistore-operations/tests/equal_metadata.py
python/equistore-torch/equistore/torch/documentation.py
python/equistore-torch/tests/labels.py

These function perform the corresponding set operation over Labels entries, and optionally return the mapping from the positions in the inputs to the position in the output.
Still TODO: 
----
:books: Documentation preview :books:: https://equistore--287.org.readthedocs.build/en/287/

Implement Labels::union and Labels::intersection

---

python/equistore-operations/equistore/operations/add.py
python/equistore-operations/equistore/operations/divide.py
python/equistore-operations/equistore/operations/multiply.py
python/equistore-operations/equistore/operations/pow.py
python/equistore-operations/equistore/operations/subtract.py
python/equistore-operations/tests/add.py
python/equistore-operations/tests/divide.py
python/equistore-operations/tests/multiply.py
python/equistore-operations/tests/pow.py
python/equistore-operations/tests/subtract.py

This also removes some `try/catch` blocks, which will help with TorchScript support (#280 is another step in this direction).
----
:books: Documentation preview :books:: https://equistore--292.org.readthedocs.build/en/292/

Fix numpy deprecation warning when using array with single entry as a scalar

---

equistore-torch/include/equistore/torch/labels.hpp
equistore-torch/src/labels.cpp
equistore-torch/src/register.cpp
python/equistore-core/equistore/core/labels.py
python/equistore-core/tests/labels.py
python/equistore-operations/equistore/operations/abs.py
python/equistore-operations/equistore/operations/divide.py
python/equistore-operations/equistore/operations/multiply.py
python/equistore-operations/equistore/operations/one_hot.py
python/equistore-operations/equistore/operations/pow.py
python/equistore-operations/equistore/operations/slice.py
python/equistore-operations/equistore/operations/unique_metadata.py
python/equistore-operations/tests/slice.py
python/equistore-operations/tests/split.py
python/equistore-torch/equistore/torch/documentation.py
python/equistore-torch/tests/labels.py

And make `Labels::__getitem__` use this instead of view.
This mean that code trying to compute some gradient will go from looking like this:
```py
data = some_function(block.values[gradient.samples["sample"].values.reshape(-1)] )
```
to this, which is much closer to the previous version
```py
data = some_function(block.values[gradient.samples["sample"]] )
```
----
:books: Documentation preview :books:: https://equistore--295.org.readthedocs.build/en/295/

Add `Labels::column` to access a single column in the values

---

python/equistore-core/equistore/core/labels.py
python/equistore-core/equistore/core/tensor.py

I mainly adjusted the docs to the new syntax for looping for `blocks` within a `TensorMap`.
----
:books: Documentation preview :books:: https://equistore--297.org.readthedocs.build/en/297/

Some minor doc tweaks

---

docs/src/reference/c/labels.rst
docs/src/reference/cxx/labels.rst
equistore-core/include/equistore.h
equistore-core/include/equistore.hpp
equistore-core/src/c_api/labels.rs
equistore-core/src/c_api/tensor.rs
equistore-core/src/io/load.rs
equistore-core/src/labels.rs
equistore-core/src/tensor/keys_to_properties.rs
equistore-core/src/tensor/keys_to_samples.rs
equistore-core/src/tensor/mod.rs
equistore-core/src/tensor/utils.rs
equistore-core/tests/cpp/labels.cpp
equistore-torch/include/equistore/torch/labels.hpp
equistore-torch/src/labels.cpp
equistore-torch/src/register.cpp
equistore-torch/tests/labels.cpp
equistore/src/c_api.rs
equistore/src/labels.rs
python/equistore-core/equistore/core/_c_api.py
python/equistore-core/equistore/core/labels.py
python/equistore-torch/equistore/torch/documentation.py
python/equistore-torch/tests/labels.py

Fix #290 
----
:books: Documentation preview :books:: https://equistore--291.org.readthedocs.build/en/291/

Keep `Labels.values` on the initial device in TorchScript

---

python/equistore-core/equistore/core/block.py
python/equistore-operations/equistore/operations/_utils.py
python/equistore-operations/equistore/operations/allclose.py
python/equistore-operations/equistore/operations/equal.py
python/equistore-operations/equistore/operations/equal_metadata.py
python/equistore-operations/tests/allclose.py
python/equistore-operations/tests/equal.py
python/equistore-operations/tests/equal_metadata.py

To support TorchScript for the equistore-operations we need to remove all try-catch block. This includes these files
* equal.py
* equal_metadata.py
* allclose.py
We remove the try-catch block by implementing a `_impl_operation` function, that returns an error message, `operation_raise` will raise, `operation` will just check if the error message is empty and depending on this return True or False.
I started with equal.py. The test for this one should pass. **I will continue with the other operations, once I get feedback that the changes in `equal.py` are good**. There is just one small change here worth mentioning: We cannot return simply a backtrace of errors, so I just concatenate the error messages
```python
-        try:
-            equal_block_raise(block_1, tensor_2.block(key))
- …
```

Removing try-catch blocks from equistore-operations

---

equistore-core/include/equistore.hpp
equistore-core/tests/cpp/blocks.cpp
equistore-core/tests/cpp/tensor.cpp
equistore-torch/include/equistore/torch/array.hpp
equistore-torch/src/array.cpp

Otherwise we can get dangling references since the rvalue immediately goes out of scope. 
Previously, this code would silently result in an empty `sizes` vector:
```cpp
auto sizes = std::vector<size_t>();
for (auto size: block.values().shape()) {
sizes.push_back(size);
}
```
Now, the code above fails to compile, and forces to put `block.values()` in a temporary.
----
:books: Documentation preview :books:: https://equistore--302.org.readthedocs.build/en/302/

Delete function to get references on rvalues in C++ API

---

setup.py

This will allow to use `pip install equistore[torch]`
----
:books: Documentation preview :books:: https://equistore--305.org.readthedocs.build/en/305/

Add equistore-torch to equistore's extras_require

---

.github/workflows/rust-tests.yml
.readthedocs.yml
CONTRIBUTING.rst
equistore-core/Cargo.toml
equistore/Cargo.toml
equistore/build.rs
equistore/src/lib.rs
python/Cargo.toml

Our dependencies are starting to do this as well (https://github.com/Stebalien/tempfile/pull/241) so we have to follow.
----
:books: Documentation preview :books:: https://equistore--308.org.readthedocs.build/en/308/

Bump minimal rust version to 1.63

---

docs/src/reference/operations/manipulation/index.rst
docs/src/reference/operations/manipulation/manipulate-dimension.rst
equistore-torch/include/equistore/torch/labels.hpp
equistore-torch/src/labels.cpp
equistore-torch/src/register.cpp
python/equistore-core/equistore/core/labels.py
python/equistore-core/tests/labels.py
python/equistore-operations/equistore/operations/__init__.py
python/equistore-operations/equistore/operations/manipulate_dimension.py
python/equistore-operations/tests/manipulate_labels_column.py
python/equistore-torch/equistore/torch/documentation.py
python/equistore-torch/tests/labels.py

This PR adds an operations to manipulate Labels as well as the Labels columns stored in TensorMaps as `keys`, `samples` or `properties`.
----
:books: Documentation preview :books:: https://equistore--299.org.readthedocs.build/en/299/

Add operations for manipulating meta data

---

docs/src/reference/operations/manipulation/index.rst
equistore-torch/include/equistore/torch/labels.hpp
equistore-torch/src/labels.cpp
equistore-torch/src/register.cpp
python/equistore-core/equistore/core/labels.py
python/equistore-core/tests/labels.py
python/equistore-operations/equistore/operations/__init__.py
python/equistore-operations/equistore/operations/manipulate_dimension.py
python/equistore-operations/tests/manipulate_dimension.py
python/equistore-torch/equistore/torch/documentation.py
python/equistore-torch/tests/labels.py

Following #299 this add an operation for permuting dimensions/columns of labels and labels in tensors. This will be useful as for sorting the rows as well.  
----
:books: Documentation preview :books:: https://equistore--316.org.readthedocs.build/en/316/

Add labels.permute and permute_dimension

---

python/equistore-operations/equistore/operations/join.py
python/equistore-operations/tests/join.py

Adds the functionality to `join` to remove the `"tensor"` column name while joining TensorMaps.
Due to torch-script I can not use a try-catch block like
```python
try:
return remove_labels_column(tensor_joined, name="tensor", axis=axis)
except EquistoreError:
return tensor_joined
```
Instead, I have to check the uniqueness on the Python level before calling `remove_labels_column`. If someone has an idea to get around the his I am happy to change this.

Remove 'tensor' of a joined TensorMap if possible

---

equistore-torch/include/equistore/torch/block.hpp
equistore-torch/src/block.cpp
equistore-torch/tests/block.cpp
python/equistore-torch/tests/block.py

Am I missing something in core that prevents this change? Or do I "just" need to refactor all tests and functions
----
:books: Documentation preview :books:: https://equistore--309.org.readthedocs.build/en/309/

Adapt torch.TensorBlock gradients() as in core.TensorBlock

---

python/equistore-operations/equistore/operations/_utils.py
python/equistore-operations/equistore/operations/add.py
python/equistore-operations/equistore/operations/allclose.py
python/equistore-operations/equistore/operations/divide.py
python/equistore-operations/equistore/operations/dot.py
python/equistore-operations/equistore/operations/empty_like.py
python/equistore-operations/equistore/operations/equal.py
python/equistore-operations/equistore/operations/equal_metadata.py
python/equistore-operations/equistore/operations/join.py
python/equistore-operations/equistore/operations/lstsq.py
python/equistore-operations/equistore/operations/multiply.py
python/equistore-operations/equistore/operations/ones_like.py
python/equistore-operations/equistore/operations/random_like.py
python/equistore-operations/equistore/operations/solve.py
python/equistore-operations/equistore/operations/subtract.py
python/equistore-operations/equistore/operations/zeros_like.py
python/equistore-operations/tests/join.py
python/equistore-operations/tests/lstsq.py
python/equistore-operations/tests/same_raise.py

In #280 we changed the naming of a lot of checking functions. However, we did not change these in the downstream methods where we use `_check_same_gradients` and `_check_same_keys`. Currently no errors are raised by all of the effected functions.
I hope I did not forgot some functions. I will also add some simple tests for this to prevent this in the future.
JWA edit: tagging relevant issue #318

Raise error when checking keys in operations

---

python/equistore-core/equistore/core/_c_lib.py

(I am using this to debug the Windows CI using a VM)
----
:books: Documentation preview :books:: https://equistore--323.org.readthedocs.build/en/323/

Allow loading the DLL for windows on ARM

---

docs/requirements.txt

Sphinx recently updated all path from string to pathlib, but some plugins we use are not yet updated.
We are hitting https://github.com/breathe-doc/breathe/issues/943 and https://github.com/pradyunsg/furo/discussions/693 for other versions of sphinx.
----
:books: Documentation preview :books:: https://equistore--325.org.readthedocs.build/en/325/

Fix documentation build by pinning sphinx

---

equistore-torch/include/equistore/torch/labels.hpp
equistore-torch/src/labels.cpp
python/equistore-operations/equistore/operations/_classes.py
python/equistore-operations/equistore/operations/_utils.py
python/equistore-operations/equistore/operations/add.py
python/equistore-operations/equistore/operations/allclose.py
python/equistore-operations/equistore/operations/divide.py
python/equistore-operations/equistore/operations/equal_metadata.py
python/equistore-operations/equistore/operations/lstsq.py
python/equistore-operations/tests/allclose.py
python/equistore-operations/tests/empty_like.py
python/equistore-operations/tests/equal.py
python/equistore-operations/tests/equal_metadata.py
python/equistore-operations/tests/ones_like.py
python/equistore-operations/tests/random_like.py
python/equistore-operations/tests/zeros_like.py
python/equistore-torch/equistore/torch/operations.py
python/equistore-torch/tests/operations/equal_metadata.py

- typing.Sequence is not TorchScript compatible
- change iterator to `range(len(keys)))`
- removed np.all operations for comparison (I don't know if this has been changed in the API, but a comparison between Labels returns a boolean in the current version)
~TODO torch script tests~
----
:books: Documentation preview :books:: https://equistore--322.org.readthedocs.build/en/322/

Make equistore.operations._utils TorchScript compatible

---

.github/workflows/rust-tests.yml
equistore/build.rs
equistore/src/c_api.rs
scripts/update-declarations.sh

The code was failing to find the shared library, and then defaulting to the static version. This caused issues when using the code from rascaline, since the corresponding Python module where using different versions of the code.
----
:books: Documentation preview :books:: https://equistore--330.org.readthedocs.build/en/330/

Make sure the Rust binding use the shared library on windows

---

python/equistore-operations/tests/to.py

Fixes #333.
----
:books: Documentation preview :books:: https://equistore--334.org.readthedocs.build/en/334/

Fix `torch.dtype` checks in `to` tests

---

python/equistore-operations/equistore/operations/_dispatch.py
python/equistore-operations/equistore/operations/reduce_over_samples.py
python/equistore-torch/tests/operations/reduce_over_samples.py

I had to eliminate the `with np.errstate()` block because it was incompatible with TorchScript.
Perhaps we can document instead in what cases the numpy warning will be given
----
:books: Documentation preview :books:: https://equistore--332.org.readthedocs.build/en/332/

Make `reduce_over_samples` torch-script-able

---

python/equistore-operations/equistore/operations/_dispatch.py
python/equistore-operations/equistore/operations/one_hot.py
python/equistore-operations/tests/one_hot.py
python/equistore-torch/tests/operations/one_hot.py

Since torchscript doesn't seem to support `torch.get_default_dtype()`, I decided to output the encoding as integers
----
:books: Documentation preview :books:: https://equistore--340.org.readthedocs.build/en/340/

Make `one_hot()` torch-script-able

---

metatensor-core/CMakeLists.txt

On windows, the list looks like
```
kernel32;advapi32;advapi32;bcrypt;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;kernel32;k …
```

De-duplicate cargo default libs

---

metatensor-torch/include/metatensor/torch/tensor.hpp
metatensor-torch/src/register.cpp
metatensor-torch/src/tensor.cpp
python/metatensor-core/metatensor/core/tensor.py
python/metatensor-core/tests/tensor.py
python/metatensor-operations/metatensor/operations/join.py
python/metatensor-operations/metatensor/operations/manipulate_dimension.py
python/metatensor-operations/metatensor/operations/reduce_over_samples.py
python/metatensor-operations/tests/join.py
python/metatensor-operations/tests/manipulate_dimension.py
python/metatensor-operations/tests/reduce_mean.py
python/metatensor-operations/tests/reduce_special_cases.py
python/metatensor-operations/tests/reduce_std.py
python/metatensor-operations/tests/reduce_sum.py
python/metatensor-operations/tests/slice.py
python/metatensor-torch/tests/operations/manipulate_dimension.py
python/metatensor-torch/tests/operations/reduce_over_samples.py
python/metatensor-torch/tests/tensor.py

- components_names now return a List[str] instead of List[list[str]]
- properties and samples names are now pluralized
the first change is for better torch script compatibility (the compiler does not know what to do with `components_names == [["something"]]`)
----
:books: Documentation preview :books:: https://metatensor--348.org.readthedocs.build/en/348/

Improve <labels>_names methods

---

metatensor-core/include/metatensor.hpp
metatensor-torch/include/metatensor/torch/block.hpp
metatensor-torch/include/metatensor/torch/labels.hpp
metatensor-torch/include/metatensor/torch/tensor.hpp
metatensor-torch/src/block.cpp
metatensor-torch/src/tensor.cpp
metatensor-torch/tests/block.cpp
metatensor-torch/tests/tensor.cpp
python/metatensor-torch/tests/tensor.py

We are already doing this for Python and it is required to avoid use after free if a function just extract a block out of a tensor map.
Fix #349 
This was surfaced by what I think is a bug in torch script compiler, but we want to do something like this anyway. The issue appears in the test code when looping over elements of a `torch.nn.ModuleDict`, which I think is executed differently than a normal loop by torch script. A similar problem (but easier to debug) would happen with a function like 
```py
def kaboom():
tensor = create_new_tensor()
return tensor.block(0)
```
----
:books: Documentation preview :books:: https://metatensor--356.org.readthedocs.build/en/356/

Keep a reference to the parent in torch's TensorBlock

---

docs/src/reference/cxx/data.rst
metatensor-core/CMakeLists.txt
metatensor-core/include/metatensor.hpp
metatensor-core/tests/cpp/blocks.cpp
metatensor-core/tests/cpp/tensor.cpp

This is something I need mainly for https://github.com/Luthaf/rascaline/issues/218 which is why I only did it for the C++ API. If other also need this from other languages, we could move the code to the C API.
----
:books: Documentation preview :books:: https://metatensor--350.org.readthedocs.build/en/350/

Clone only the metadata of a TensorMap/TensorBlock in C++

---

docs/requirements.txt

I get an error when running `tox -e docs` locally, see also https://github.com/sphinx-doc/sphinx/issues/11662#issuecomment-1710192959.
----
:books: Documentation preview :books:: https://metatensor--358.org.readthedocs.build/en/358/

Pin sphinx for docs again

---

CONTRIBUTING.rst
python/metatensor-operations/metatensor/operations/_dispatch.py
python/metatensor-operations/tests/to.py
tox.ini

The first two commits are removing the existing dependencies on torch in the operations. The last commit adds another tox environment that does not have torch as dependency. I updated the CONTRIBUTING.rst, that was the only occurrence of `operations-tests` I could find.
----
:books: Documentation preview :books:: https://metatensor--365.org.readthedocs.build/en/365/

Test operations notorch

---

metatensor-torch/include/metatensor/torch/labels.hpp
metatensor-torch/src/labels.cpp
metatensor-torch/src/register.cpp
python/metatensor-core/metatensor/core/labels.py
python/metatensor-operations/metatensor/operations/to.py
python/metatensor-torch/metatensor/torch/documentation.py
python/metatensor-torch/tests/labels.py
python/metatensor-torch/tests/operations/to.py

The code is a bit complicated:
- `view().to_owned()` used to make copies of labels (`Labels.to()` works in-place for now, perhaps it should return a different object like `Tensor.to()`)
- `Labels.to()` only accepts `torch.device` (not str), so I'm having to use a `torch.device` from a block
----
:books: Documentation preview :books:: https://metatensor--361.org.readthedocs.build/en/361/

Move labels to device in `to()`

---

docs/src/get-started/installation.rst

----
:books: Documentation preview :books:: https://metatensor--371.org.readthedocs.build/en/371/

Fix wrong directory in installation C/C++ library

---

python/metatensor-core/metatensor/__init__.py

Minor issue, low, but seems like an easy fix. To import the LabelsEntry from core one has to do
```python
from metatensor.core.labels import LabelsEntry
```
while from torch it can be imported like
```python
from metatensor.torch import LabelsEntry
```
To me it seems intuitive if we could also import LabelsEntry from core like this
```python
from metatensor.core import LabelsEntry
```
----
:books: Documentation preview :books:: https://metatensor--373.org.readthedocs.build/en/373/

make LabelsEntry available to import from core

---

metatensor-torch/include/metatensor/torch/labels.hpp
metatensor-torch/src/labels.cpp
metatensor-torch/src/tensor.cpp

Both during iteration over labels and `tensor.block(key)`. This brings this code
```py
for key in tensor.keys:
block = tensor.block(key)
```
from 40 ms to 2.5 ms (with a tensor containing 30 block) when using metatensor-torch. This is still a bit slower than metatensor-core at 600 us, but I can't find obvious performance problem in a profiler.
----
:books: Documentation preview :books:: https://metatensor--380.org.readthedocs.build/en/380/

Fix performance issues coming from backtrace collection

---

python/metatensor-core/setup.py
python/metatensor-torch/setup.py
scripts/build-python.sh
tox.ini

Since building metatensor-torch wheel requires a version of metatensor-torch available through pip, we use `dir2pi` from https://pypi.org/project/pip2pi/ to generate a pip-compatible server serving freshly built wheels. The tests also moved to a bash script since we need to start an HTTP server in the background, and cleanup once we exit.
----
:books: Documentation preview :books:: https://metatensor--387.org.readthedocs.build/en/387/

Add a test building metatensor-torch from sdist

---

.github/workflows/build-wheels.yml
python/metatensor-operations/setup.py
python/metatensor-torch/setup.py
scripts/package-core.sh
scripts/package-torch.sh
setup.py

The metatensor Python package had the wrong metatadata, and all artefacts where uploaded to all tags.
----
:books: Documentation preview :books:: https://metatensor--391.org.readthedocs.build/en/391/

Correct issues with automatic artefacts upload from CI

---

.github/workflows/torch-tests.yml
metatensor-torch/CMakeLists.txt
metatensor-torch/tests/utils/mod.rs
python/metatensor-torch/tests/block.py
python/metatensor-torch/tests/labels.py
python/metatensor-torch/tests/operations/split.py
python/metatensor-torch/tests/tensor.py

PyTorch 2.1 has just been released, we need some changes to fully support it!
----
:books: Documentation preview :books:: https://metatensor--395.org.readthedocs.build/en/395/

Updates for PyTorch 2.1

---

docs/src/reference/torch/index.rst

----
:books: Documentation preview :books:: https://metatensor--397.org.readthedocs.build/en/397/

Add operations to metatensor torch documentation

---

.codecov.yml
.github/workflows/coverage.yml
.gitignore
CONTRIBUTING.rst
README.md
tox.ini

As a starting point this PR adds collecting the coverage for the Python code.
----
:books: Documentation preview :books:: https://metatensor--381.org.readthedocs.build/en/381/

Add Python coverage

---

.github/workflows/coverage.yml
python/metatensor-operations/metatensor/operations/_dispatch.py
python/metatensor-operations/metatensor/operations/reduce_over_samples.py
python/metatensor-operations/tests/reduce_special_cases.py
python/metatensor-torch/tests/operations/reduce_over_samples.py
tox.ini

In the metatensor-core version, the `index` must be converted to a torch tensor before passing it to `index_add`. Since it comes from the Labels, it is a numpy array by default.
In the metatensor-torch version, `unique_with_inverse` does not work when reducing to a single sample
----
:books: Documentation preview :books:: https://metatensor--404.org.readthedocs.build/en/404/

Two fixes for sample reduction with torch

---

.github/workflows/coverage.yml
.github/workflows/python-tests.yml
.github/workflows/rust-tests.yml
.github/workflows/torch-tests.yml

Otherwise CI fails trying to pull a version from which there are no artifacts yet.
----
:books: Documentation preview :books:: https://metatensor--408.org.readthedocs.build/en/408/

Fix the version of sccache we pull from github

---

.github/workflows/python-tests.yml
CONTRIBUTING.rst
pyproject.toml
python/metatensor-core/metatensor/__init__.py
python/metatensor-core/metatensor/tensor.py
python/metatensor-core/metatensor/version.py
python/metatensor-core/pyproject.toml
python/metatensor-core/tests/serialization.py
python/metatensor-operations/metatensor/operations/__init__.py
python/metatensor-operations/pyproject.toml
python/metatensor-operations/tests/slice.py
python/metatensor-operations/tests/split.py
python/metatensor-torch/metatensor/torch/__init__.py
python/metatensor-torch/metatensor/torch/version.py
python/metatensor-torch/pyproject.toml
tox.ini

Removed support for Python 3.7 since it reaches its [end of life](https://www.python.org/downloads/release/python-3717/). 
@Luthaf you mentioned once there is some leftover code which is only there due to Python 3.7? I checked but haven't found anything.
Also should we update the changelog for this?
----
:books: Documentation preview :books:: https://metatensor--425.org.readthedocs.build/en/425/

Bump min Python version 3.7

---

tox.ini

This makes already existing descriptions available via `tox list`
```
default environments:
lint                   -> lint the Python code with flake8 (code linter), black (code formatter), and isort (sorting of imports)
core-tests             -> Run the tests of the metatensor-core Python package
operations-numpy-tests -> Run the tests of the metatensor-operations Python package using numpy arrays
operations-torch-tests -> Run the tests of the metatensor-operations Python package using torch arrays
torch-tests            -> Run the tests of the metatensor-torch Python package
docs-tests             -> Run the doctests defined in any metatensor package
additional environments:
format                 -> Abuse tox to do actual formatting on all files.
docs                   -> build the …
```

Move `tox.ini` environment comments to descriptions

---

python/metatensor-torch/metatensor/torch/documentation.py

Fixes #434 
----
📚 Documentation preview 📚: https://metatensor--435.org.readthedocs.build/en/435/

Fix documentation for `metatensor.torch.Labels.to`

---

metatensor-core/CMakeLists.txt
metatensor-core/cmake/tempdir.cmake
metatensor-core/src/c_api/mod.rs
metatensor/src/lib.rs
scripts/clean-python.sh

There where some changes in determining workspaces members, which broke the code we use to get the list of static libraries to link with.
We now list these libraries from a temporary directory instead of a subdirectory in `target`.
It might make sense to release this as 0.1.1 for metatensor-core and metatensor rust, to be able to use these inside rascaline.
----
📚 Documentation preview 📚: https://metatensor--438.org.readthedocs.build/en/438/

Fix build with cargo 1.75

---

metatensor-core/CHANGELOG.md
metatensor-core/Cargo.toml
metatensor/CHANGELOG.md
metatensor/Cargo.toml

Incorporating mainly #438 and #419.
----
📚 Documentation preview 📚: https://metatensor--440.org.readthedocs.build/en/440/

Release -core and -rust v0.1.1

---

.readthedocs.yml
docs/src/reference/rust/backlink.html
tox.ini

This is a bandaid to integrate the rust API reference a bit better with the main doc website. 
I also tried to load the rust reference inside an iframe in the main doc website, but this makes sending links to a specific function in the documentation a lot harder, so I settled for this solution instead.
----
📚 Documentation preview 📚: https://metatensor--443.org.readthedocs.build/en/443/

Add a link back to the main documentation in rust reference

---

metatensor-torch/src/atomistic.cpp

And not against metatensor-core version. Otherwise people just building and running a model get a warning they can't do anything with!
> [W atomistic.cpp:1108] Warning: Current metatensor version (0.2.0-dev8) is not compatible with the version (0.3.0.dev2) used to export the model at 'exported-model.pt'; proceed at your own risk. (function check_atomistic_model)
----
📚 Documentation preview 📚: https://metatensor--445.org.readthedocs.build/en/445/

Check recorded version in models against metatensor-torch's version

---

.github/workflows/rust-tests.yml
metatensor-core/CMakeLists.txt
python/metatensor-operations/tests/slice.py

MinGW is used as the Windows ABI for Julia.
`rustc` creates DLL files without a `lib` prefix, which does not match the expectations of most tools in the MinGW world.
This PR tries to enable CI for this target, and fix the CMake build to pass the right arguments.
----
📚 Documentation preview 📚: https://metatensor--441.org.readthedocs.build/en/441/

Fix build with MinGW on windows

---

CONTRIBUTING.rst

In the `CONTRIBUTING.rst` the description of the master branch as required target branch is not very clear and has a typo. I tried to improve the sentence.
----
📚 Documentation preview 📚: https://metatensor--462.org.readthedocs.build/en/462/

Improve formulation of master branch description

---

python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
python/metatensor-torch/tests/atomistic/ase_calculator.py

This fix calls to `atoms.get_properties["stress"]`, which would otherwise fail with `ValueError: stress has bad shape: (3, 3)`
----
📚 Documentation preview 📚: https://metatensor--463.org.readthedocs.build/en/463/

Return stress in Voigt notation for ASE calculator

---

python/metatensor-learn/metatensor/learn/data/collate.py
python/metatensor-learn/metatensor/learn/data/dataloader.py
python/metatensor-learn/metatensor/learn/data/dataset.py
python/metatensor-learn/tests/collate.py
python/metatensor-learn/tests/dataset.py
python/metatensor-learn/tests/utils.py
python/metatensor-operations/metatensor/operations/abs.py
python/metatensor-operations/metatensor/operations/checks.py
python/metatensor-operations/metatensor/operations/equal_metadata.py
python/metatensor-operations/metatensor/operations/manipulate_dimension.py
python/metatensor-operations/metatensor/operations/unique_metadata.py
python/metatensor-torch/metatensor/torch/atomistic/documentation.py
python/metatensor-torch/metatensor/torch/atomistic/model.py

Black has been updated for 23.12 to 24.1 and makes the linter fail in existing PRs.
I just run `tox -e format`
----
📚 Documentation preview 📚: https://metatensor--465.org.readthedocs.build/en/465/

Format with new black version 24.1

---

python/metatensor-learn/metatensor/learn/nn/linear.py

Fix #464 (not really a fix, but does give description why we can do use the first block's dtype)
----
📚 Documentation preview 📚: https://metatensor--481.org.readthedocs.build/en/481/

Fix #464 add comment in `metatensor-learn` linear that dtype is constant

---

.github/workflows/coverage.yml

We where using v3, which is currently failing. Let's see if this one works better!
This is exactly the same as https://github.com/lab-cosmo/metatensor/pull/488, but as a PR from the same repo instead of a fork (since that's one of the big change in this new version). See https://github.com/lab-cosmo/metatensor/actions/runs/7787428418/job/21234557857?pr=488 for the corresponding CI log for the branch from a fork.
----
📚 Documentation preview 📚: https://metatensor--491.org.readthedocs.build/en/491/

Upgrade to codecov-action v4

---

python/examples/learn/2-indexed-dataset.py
python/metatensor-learn/CHANGELOG.md
python/metatensor-learn/metatensor/learn/data/collate.py
python/metatensor-learn/metatensor/learn/data/dataset.py
python/metatensor-learn/tests/collate.py
python/metatensor-learn/tests/dataloader.py
python/metatensor-learn/tests/dataset.py
python/metatensor-learn/tests/utils.py

Closes #485, and removes pluralization of the data field `sample_ids` -> `sample_id` in both `group` and `group_and_join` collate functions, and `IndexedDataset`
----
📚 Documentation preview 📚: https://metatensor--487.org.readthedocs.build/en/487/

Fix collate fn `group_and_join` for `ScriptObject`s that aren't TensorMaps

---

python/metatensor-learn/CHANGELOG.md
python/metatensor-learn/metatensor/learn/nn/module_map.py
python/metatensor-torch/tests/learn/linear.py
python/metatensor-torch/tests/learn/module_map.py

This needs to be done for to support torch.jit.save see issue #410
----
📚 Documentation preview 📚: https://metatensor--489.org.readthedocs.build/en/489/

`metatensor-learn` remove usage of Labels.range

---

python/metatensor-operations/metatensor/operations/sort.py
python/metatensor-operations/tests/sort.py
python/metatensor-torch/tests/operations/sort.py

Fixes #470
- Splitting sorted tensors into an ascending and descending so the fix can be more robustly tested
- Adding dispatched arange_like to create inverse mapping for reasigning samples in gradients
Waiting till https://github.com/lab-cosmo/metatensor/pull/479 is merged to also add finite difference test
----
📚 Documentation preview 📚: https://metatensor--480.org.readthedocs.build/en/480/

Fix #470 non adapted sample indices in gradients during sorting

---

python/metatensor-learn/metatensor/learn/nn/linear.py
python/metatensor-learn/tests/linear.py
python/metatensor-learn/tests/module_map.py
python/metatensor-learn/tests/utils.py
python/metatensor-operations/metatensor/operations/slice.py
python/metatensor-torch/tests/atomistic/ase_calculator.py
python/metatensor-torch/tests/learn/linear.py
python/metatensor-torch/tests/learn/module_map.py
python/metatensor-torch/tests/learn/utils.py
tox.ini

The tests for `.learn` inside metatensor-torch where still using numpy in some places, I've removed the corresponding code and in general separated tests using `metatensor.Labels` (in `metatensor-learn`) and tests using `metatensor.torch.Labels` (in `metatensor-torch`)
----
📚 Documentation preview 📚: https://metatensor--493.org.readthedocs.build/en/493/

Cleanup metatensor-learn tests

---

.github/workflows/build-wheels.yml
.github/workflows/python-tests.yml
scripts/build-all-wheels.sh
tox.ini

It takes a lot of CI time for very few issues caught. For now the code remains in tox for easier local debugging of future wheel building issues, it might be removed later. The wheels and sdists are checked with twine in a separate CI job.
----
📚 Documentation preview 📚: https://metatensor--497.org.readthedocs.build/en/497/

 Remove Python build-tests from CI

---

docs/src/learn/reference/data/index.rst
docs/src/learn/reference/nn/index.rst
python/metatensor-core/metatensor/__init__.py
python/metatensor-learn/metatensor/learn/__init__.py
python/metatensor-learn/metatensor/learn/data/dataloader.py
python/metatensor-learn/metatensor/learn/data/dataset.py
python/metatensor-torch/metatensor/torch/__init__.py

Otherwise it gets confusing what is coming from metatensor-learn and what is coming from metatensor-operations. This was already different between -core and -torch anyway, so this PR makes everything the same, following the current -core version.
----
📚 Documentation preview 📚: https://metatensor--502.org.readthedocs.build/en/502/

Do not re-export metatensor-learn

---

metatensor-core/Cargo.toml

The latest version of `ahash` requires rustc 1.72, which for now we don't want to enforce.
----
📚 Documentation preview 📚: https://metatensor--505.org.readthedocs.build/en/505/

Pin last rustc 1.65 version of ahash

---

metatensor-core/CMakeLists.txt
metatensor-core/Cargo.toml
scripts/package-core.sh

This makes sure a given version of metatensor-core will always use the exact same dependencies version, saving us a lot of headache in the long term.
In particular, this would prevent the issue in https://github.com/Luthaf/rascaline/pull/280 from happening.

Generate and use a lockfile in metatensor-core

---

docs/generate_examples/conf.py
docs/generate_examples/generate-examples.py
docs/src/conf.py

I also added some explanations why we are using two sphinx projects. Let me know if this makes things a bit clearer.
I had to rename the folder `scripts/sphinx-gallery` to `gallery` to not infer with the actual sphinx gallery project. I am not sure about the name though.
----
📚 Documentation preview 📚: https://metatensor--511.org.readthedocs.build/en/511/

Share `sphinx_gallery_conf` within documentation building

---

.github/workflows/build-wheels.yml
.github/workflows/coverage.yml
.github/workflows/docs.yml
.github/workflows/julia-tests.yml
.github/workflows/python-tests.yml
.github/workflows/rust-tests.yml
.github/workflows/torch-tests.yml
.readthedocs.yml
metatensor-torch/tests/utils/mod.rs
python/metatensor-core/pyproject.toml
python/metatensor-torch/pyproject.toml
python/scripts/rustc-manylinux2014_x86_64/Dockerfile
tox.ini

This does multiple upgrades to the CI environement:
- ~Use M1 runners for macOS CI;~ EDIT: no longer part of this PR, will be done later
- Use rustc 1.75 to build the linux wheels 
- Use Python 3.12 instead of 3.11 as out highest supported version
- Use Torch 2.2 for the C++ tests
----
📚 Documentation preview 📚: https://metatensor--503.org.readthedocs.build/en/503/

Upgrade CI

---

python/metatensor-core/metatensor/data/array.py

Trying to save a float32 TensorMap will result in a slightly confusing error message, hopefully this improves it.
----
📚 Documentation preview 📚: https://metatensor--523.org.readthedocs.build/en/523/

Better error message when saving TensorMap with dtype != float64

---

metatensor-torch/cmake/metatensor_torch-config.in.cmake

Otherwise wheels built with torch x.y.0 can not be used to build e.g. rascaline-torch with torch x.y.z
This hit me today with the release of torch 2.2.1, and I had to purge the pip cache to re-create metatensor-torch wheel.
----
📚 Documentation preview 📚: https://metatensor--527.org.readthedocs.build/en/527/

Don't check patch torch version when loading from CMake

---

.github/dependabot.yml

Updating the github actions for our CI is an repeating and tedious work. Also we always forget to update some in the jungle of actions we use.
Maybe [Githubs dependabot](https://docs.github.com/en/code-security/dependabot) can help us 🤖. This is a test which checks the dependencies of all actions once per month and groups all of them into one commit. If this is still to noisy or introduces too many errors we can disable this again.
- ~[ ] CHANGELOG updated with public API or any other important changes?~
----
📚 Documentation preview 📚: https://metatensor--530.org.readthedocs.build/en/530/

Use dependabot 🤖 to update our github actions

---

python/metatensor-torch/metatensor/torch/atomistic/model.py
python/metatensor-torch/metatensor/torch/atomistic/outputs.py
python/metatensor-torch/tests/atomistic/ase_calculator.py

When `check_consistency=True`, we also want to check that the data given by the engine matches what we expects.
----
📚 Documentation preview 📚: https://metatensor--528.org.readthedocs.build/en/528/

Check the `selected_atoms` given by the engine

---

docs/src/devdoc/versions.rst
rust/metatensor-sys/Cargo.toml
rust/metatensor/Cargo.toml

CI is failing on master due to a bad interaction between #535 and #536  (the release was merged first, but the code also needed to be updated for the rust crate split)
----
📚 Documentation preview 📚: https://metatensor--538.org.readthedocs.build/en/538/

Update version number in metatensor-sys

---

rust/metatensor/CHANGELOG.md
rust/metatensor/Cargo.toml

This will be the first version using #535. Future changes to metatensor-core will be made accessible from rust by releasing new versions of the `metatensor-sys` crate instead of having to update the Rust API.
----
📚 Documentation preview 📚: https://metatensor--547.org.readthedocs.build/en/547/

Release metatensor-rust v0.1.4

---

.github/workflows/torch-tests.yml
metatensor-core/tests/cmake-project/CMakeLists.txt
metatensor-torch/tests/cmake-project/CMakeLists.txt
tox.ini

We claim to support CMake 3.16, but we did not have a test checking this for metatensor-torch. So let's add it!
----
📚 Documentation preview 📚: https://metatensor--544.org.readthedocs.build/en/544/

Run C++ Torch tests with Cmake 3.16 in CI

---

rust/metatensor/CHANGELOG.md
rust/metatensor/Cargo.toml
rust/metatensor/src/lib.rs

Rascaline is using these to implement a custom `Array`.
----
📚 Documentation preview 📚: https://metatensor--549.org.readthedocs.build/en/549/

Re-export the C API in Rust bindings

---

.github/workflows/build-wheels.yml
.github/workflows/rust-tests.yml
python/metatensor-core/setup.py
python/metatensor-torch/build-backend/backend.py
python/metatensor-torch/pyproject.toml
python/metatensor-torch/setup.py
scripts/build-all-wheels.sh
scripts/package-core.sh
scripts/package-torch.sh
scripts/update-declarations.sh

This makes sdist creation for metatensor-torch a lot faster by no requiring `torch` to be installed when building the sdist (but still required it to build the wheel).
This also automatically package the C++ version of metatensor-core and metatensor-torch in their respective `setup.py`, so we can never forget to run them when generating the sdist.
----
📚 Documentation preview 📚: https://metatensor--540.org.readthedocs.build/en/540/

Improve sdist generation

---

python/metatensor-torch/metatensor/torch/atomistic/outputs.py

This fixes a small device bug in the atomistic model checks. The predictions can be on any device, but they were being compared to a CPU Labels object.
I am not sure how to test this however
- [?] Tests updated (for new features and bugfixes)?
----
📚 Documentation preview 📚: https://metatensor--552.org.readthedocs.build/en/552/

Fix device in atomistic model check

---

metatensor-torch/CHANGELOG.md
metatensor-torch/include/metatensor/torch/atomistic/model.hpp
metatensor-torch/src/atomistic/model.cpp
metatensor-torch/src/register.cpp
metatensor-torch/tests/atomistic.cpp
python/examples/atomistic/1-export-atomistic-model.py
python/examples/atomistic/2-running-ase-md.py
python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
python/metatensor-torch/metatensor/torch/atomistic/documentation.py
python/metatensor-torch/metatensor/torch/atomistic/model.py
python/metatensor-torch/metatensor/torch/atomistic/outputs.py
python/metatensor-torch/tests/atomistic/ase_calculator.py
python/metatensor-torch/tests/atomistic/metadata.py
python/metatensor-torch/tests/atomistic/model.py
python/metatensor-torch/tests/atomistic/neighbors.py

The dtype is picked by the model, and the engine has to convert data on input/output to whatever it needs (similar to how different devices are handled).
----
📚 Documentation preview 📚: https://metatensor--551.org.readthedocs.build/en/551/

Add ModelCapabilities::dtype, picked by the model

---

julia/deps/build_local.jl
metatensor-core/tests/utils/mod.rs
python/metatensor-core/setup.py
python/metatensor-torch/setup.py

We use cmake's `--parallel` flag to speed up compilation for Python builds
----
📚 Documentation preview 📚: https://metatensor--557.org.readthedocs.build/en/557/

Parallelize compilation with cmake

---

docs/src/core/reference/c/index.rst
docs/src/core/reference/cxx/index.rst
docs/src/core/reference/python/index.rst
metatensor-core/CHANGELOG.md
metatensor-core/Cargo.toml
metatensor-core/src/tensor/mod.rs
rust/metatensor-sys/Cargo.toml
rust/metatensor/src/lib.rs

This mainly includes #573, which we also need in rascaline.
----
📚 Documentation preview 📚: https://metatensor--574.org.readthedocs.build/en/574/

Release metatensor-core v0.1.5

---

metatensor-torch/include/metatensor/torch/atomistic/model.hpp
metatensor-torch/src/atomistic/model.cpp
metatensor-torch/src/register.cpp
metatensor-torch/tests/atomistic.cpp
python/metatensor-torch/metatensor/torch/atomistic/documentation.py
python/metatensor-torch/metatensor/torch/atomistic/model.py
python/metatensor-torch/metatensor/torch/atomistic/outputs.py
python/metatensor-torch/tests/atomistic/model.py

This makes it clearer what is part of the standard and what is not, and allow code to check for either `my-code::custom-output` or `custom-output` to stay compatible with models before and after a new standard is defined.
----
📚 Documentation preview 📚: https://metatensor--565.org.readthedocs.build/en/565/

Enforce that the name of experimental outputs looks like `<domain>::<output>`

---

metatensor-core/cmake/tempdir.cmake

Some windows version of mktemp don't create it. This was required to get the code to build on conda-forge (https://github.com/conda-forge/staged-recipes/pull/25986)
----
📚 Documentation preview 📚: https://metatensor--575.org.readthedocs.build/en/575/

Make sure the temporary directory is always created

---

metatensor-core/CMakeLists.txt

This was useful in debugging https://github.com/conda-forge/staged-recipes/pull/25986
----
📚 Documentation preview 📚: https://metatensor--577.org.readthedocs.build/en/577/

More logging when we fail to determine cargo static libs

---

.github/workflows/build-wheels.yml
.github/workflows/python-tests.yml
.github/workflows/torch-tests.yml
docs/src/atomistic/reference/cxx/models.rst
docs/src/atomistic/reference/models/index.rst
docs/src/installation.rst
metatensor-torch/CHANGELOG.md
metatensor-torch/CMakeLists.txt
metatensor-torch/include/metatensor/torch/atomistic/model.hpp
metatensor-torch/src/atomistic/model.cpp
metatensor-torch/src/internal/shared_libraries.cpp
metatensor-torch/src/internal/shared_libraries.hpp
metatensor-torch/src/register.cpp
python/metatensor-torch/build-backend/backend.py
python/metatensor-torch/metatensor/torch/atomistic/__init__.py
python/metatensor-torch/metatensor/torch/atomistic/_extensions.py
python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
python/metatensor-torch/metatensor/torch/atomistic/documentation.py
python/metatensor-torch/metatensor/torch/atomistic/model.py
python/metatensor-torch/setup.py
python/metatensor-torch/tests/atomistic/ase_calculator.py
tox.ini

Fix #512 
This PR adds functionality to load the extensions a model uses (in practise defined as the extensions that where loaded when exporting a model) after the fact. This will enable using a model using rascaline without doing an `import rascaline.torch` before; or in LAMMPS.
An extensions loaded from `<site-package>/some/path.so` will be recorded as `some/path.so`, and we will try to load it from `<extensions_directory>/some/path.so`, `<current_directory>/some/path.so` and just as `path` (letting the OS try to find this lib, which enables stuff like `LD_LIBRARY_PATH` to work).
Should we allow for multiple `extensions_directory`? So a user could add a Python's `<site-packages>` with the right set of packages to the list, allowing to use some newer versions of the extensions together …

Load TorchScript extensions used by a model

---

metatensor-torch/CHANGELOG.md
metatensor-torch/include/metatensor/torch/atomistic/system.hpp
metatensor-torch/src/atomistic/system.cpp
metatensor-torch/src/register.cpp
python/metatensor-torch/metatensor/torch/atomistic/documentation.py
python/metatensor-torch/tests/atomistic/systems.py

This enable workflows where a first part of the calculation generates some data that will be used as input in a second part of the calculations (e.g. soap model to generate charges then used by lode)
----
📚 Documentation preview 📚: https://metatensor--578.org.readthedocs.build/en/578/

Allow to override custom data inside a System

---

.github/workflows/comment-wheels-pr.yml

There was a typo using the first artifact instead of the current one
----
📚 Documentation preview 📚: https://metatensor--582.org.readthedocs.build/en/582/

Use the right link for preview wheels in PR

---

metatensor-torch/src/atomistic/model.cpp
metatensor-torch/src/atomistic/system.cpp
python/metatensor-torch/metatensor/torch/atomistic/_extensions.py
python/metatensor-torch/metatensor/torch/atomistic/model.py
tox.ini

The main change is the order of operations when loading a model: first try to load extensions, THEN complain if extensions are not loaded.
----
📚 Documentation preview 📚: https://metatensor--584.org.readthedocs.build/en/584/

More tweaks for loading extensions

---

python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
python/metatensor-torch/tests/atomistic/neighbors.py
python/metatensor-torch/tests/atomistic/systems.py
tox.ini

The previous code was doing too many Python loops, and computing the neighbors took ~1s for only 40 atoms. It is now down to 20ms.
----
📚 Documentation preview 📚: https://metatensor--586.org.readthedocs.build/en/586/

Much faster adapter from ASE NL to metatensor NL

---

metatensor-torch/cmake/metatensor_torch-config.in.cmake

This is a follow up to #527, allowing to build metatensor-torch against torch x.y.z and then use it with x.y.0 (which would otherwise be disabled by `find_package(Torch)`
----
📚 Documentation preview 📚: https://metatensor--596.org.readthedocs.build/en/596/

Also exclude torch patch version from find_package

---

python/metatensor-learn/CHANGELOG.md
python/metatensor-learn/metatensor/learn/nn/module_map.py
python/metatensor-learn/tests/linear.py
python/metatensor-learn/tests/module_map.py
python/metatensor-torch/tests/learn/module_map.py

Fix #554
This moves metatensor data to a new device when running forward(), ensuring `ModuleMap` can be used on non-cpu devices.
----
📚 Documentation preview 📚: https://metatensor--595.org.readthedocs.build/en/595/

Move data to the right device in ModuleMap::forward

---

.github/workflows/build-wheels.yml
python/metatensor-torch/setup.py
scripts/create-torch-versions-range.py

We now set `install_requires`/`Requires-Dist:` fields to the specific set of torch version a given metatensor-torch wheel is compatible with. This happen both when building a wheel locally (we set `torch == x.y.*`) and when merging wheels on CI (we merge the individual requirements above into `torch >=1.12,<2.4`)
----
📚 Documentation preview 📚: https://metatensor--592.org.readthedocs.build/en/592/

Record the compatible torch version in wheel METADATA

---

.github/dependabot.yml
.github/workflows/docs.yml

This should tell the bot to open one PR for ALL GitHub action dependencies and not one per package as in #601.
Let's see if this is working. To test I revert the change of #601. 🤞
----
📚 Documentation preview 📚: https://metatensor--602.org.readthedocs.build/en/602/

Re-enable grouping for GitHub action updates

---

.github/workflows/build-wheels.yml
.github/workflows/julia-tests.yml
.github/workflows/python-tests.yml
.github/workflows/rust-tests.yml
.github/workflows/torch-tests.yml
metatensor-torch/tests/utils/mod.rs
python/metatensor-core/tests/_tests_utils.py
python/metatensor-core/tests/blocks.py
python/metatensor-core/tests/tensor.py
python/metatensor-learn/tests/_tests_utils.py
python/metatensor-learn/tests/module_map.py
python/metatensor-torch/tests/_tests_utils.py
python/metatensor-torch/tests/atomistic/ase_calculator.py
python/metatensor-torch/tests/atomistic/systems.py
python/metatensor-torch/tests/block.py
python/metatensor-torch/tests/labels.py
python/metatensor-torch/tests/learn/_tests_utils.py
python/metatensor-torch/tests/learn/module_map.py
python/metatensor-torch/tests/tensor.py
tox.ini

This is not doing much, just build wheels for torch v2.3 and using it for tests on CI
----
📚 Documentation preview 📚: https://metatensor--590.org.readthedocs.build/en/590/

Add support for torch v2.3

---

metatensor-core/CMakeLists.txt

This should fix the build on MSVC with rustc 1.78. I'm hotfixing this for now, the issue is also reported on the rust repository to see if there is a better way.
----
📚 Documentation preview 📚: https://metatensor--605.org.readthedocs.build/en/605/

Force the inclusion of bcrypt in Cargo default link libraries

---

metatensor-core/CMakeLists.txt
metatensor-core/Cargo.toml

It needs to link to BCrypt on Windows which is non trivial with our build system, and we don't actually need it.
----
📚 Documentation preview 📚: https://metatensor--612.org.readthedocs.build/en/612/

Remove dependency on getrandom

---

docs/generate_examples/conf.py

This reduces the size of the docs by 10 MiB (there where two 5MiB copies of the base64-encoded HTML video), and the rendering time went from 20s to 10s for the ase-md example.
----
📚 Documentation preview 📚: https://metatensor--610.org.readthedocs.build/en/610/

Use a custom scraper in sphinx-gallery for animations

---

.github/workflows/docs.yml
README.md
docs/extensions/versions_list.py
docs/src/conf.py
metatensor-torch/README.md
pyproject.toml
python/metatensor-core/pyproject.toml
python/metatensor-learn/pyproject.toml
python/metatensor-operations/pyproject.toml
python/metatensor-torch/metatensor/torch/atomistic/outputs.py
python/metatensor-torch/pyproject.toml
rust/metatensor-sys/Cargo.toml
rust/metatensor/Cargo.toml

This will help keeping the size of this repository under control. The documentation will be deployed to https://github.com/lab-cosmo/metatensor-docs, which is then served at https://docs.metatensor.org/
This does not change how developers write the documentation or build it locally, only how we create the public documentation website.
----
📚 Documentation preview 📚: https://metatensor--609.org.readthedocs.build/en/609/

Deploy documentation on a separate repository

---

.github/workflows/build-wheels.yml
python/metatensor-core/setup.py
python/metatensor-torch/setup.py

This fixes building wheels which depend on each other. Previously on some systems `CMAKE_INSTALL_LIBDIR` would be set to `lib64` instead of `lib`, and cmake could not find the configuration files in the expected `<site-packages>/metatensor/lib`.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1497114260.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1497186724.zip)

Set CMAKE_INSTALL_LIBDIR in `setup.py` to match assumptions in `_c_lib.py`

---

metatensor-core/CHANGELOG.md
metatensor-core/Cargo.toml
rust/metatensor-sys/Cargo.toml
rust/metatensor-sys/build.rs

Same as #617 but when building the code to be used from Rust (i.e. rascaline)
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1497635853.zip)

Also set CMAKE_INSTALL_LIBDIR in metatensor-sys

---

.github/workflows/build-wheels.yml

This should allow to catch things like #617 earlier.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1501781632.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1501861125.zip)

Build wheels on CI whenever the build system code changes

---

python/metatensor-torch/build-backend/backend.py
python/metatensor-torch/pyproject.toml
python/metatensor-torch/setup.py

We need it early to be able to unpack the C++ sources tarball. 
Related to #626 
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1526907502.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1527154695.zip)

Require cmake to build metatensor-torch wheels

---

python/metatensor-learn/CHANGELOG.md
python/metatensor-learn/metatensor/learn/nn/layer_norm.py
python/metatensor-learn/tests/layer_norm.py

Fix the implementation of `LayerNorm` and `InvariantLayerNorm` to calculate the mean and variance of blocks over all dimensions except the samples, such that transformations are applied to samples independently. The current implementation calculates these statistics over the samples, thus applying a BatchNorm-esque transformation.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1534277939.zip)

Make `LayerNorm` sample independent

---

python/metatensor-learn/CHANGELOG.md
python/metatensor-learn/metatensor/learn/data/_namedtuple.py
python/metatensor-learn/metatensor/learn/data/collate.py
python/metatensor-learn/metatensor/learn/data/dataset.py
python/metatensor-learn/tests/_tests_utils.py
python/metatensor-learn/tests/dataloader.py
python/metatensor-learn/tests/dataset.py

Fix #621 
We use a custom `namedtuple` function to allow storing data where the name is not a python identifier. These fields can be accessed by their numeric index `sample[3]` or using a string name `sample["some weird name"]`. Previous code should work in the exact same way.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1543863592.zip)

Allow non-identifiers as fields in Dataset

---

python/metatensor-torch/metatensor/torch/atomistic/_extensions.py

If someone is using a global python installation (like the one from their Linux distribution), most of the packages will be installed in the user site prefix. If it is enabled, we also consider it when copying extensions out of the site-packages.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1543467487.zip)

Also consider user site prefix when collecting extensions

---

metatensor-torch/src/atomistic/system.cpp
python/metatensor-torch/tests/atomistic/neighbors.py

This small PR updated the way the `NeighborsAutograd::backward` computes the `positions_grad`. Now, instead of iterating over the samples (i.e. list of neighbors), the operation is vectorized with `torch::index_add`.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1549000929.zip)

Vectorized NeighborsAutograd::backward

---

metatensor-core/CHANGELOG.md
metatensor-torch/CHANGELOG.md
metatensor-torch/include/metatensor/torch/block.hpp
metatensor-torch/src/block.cpp
metatensor-torch/src/register.cpp
metatensor-torch/tests/block.cpp
python/metatensor-core/metatensor/block.py
python/metatensor-core/tests/blocks.py
python/metatensor-torch/metatensor/torch/documentation.py
python/metatensor-torch/tests/block.py

add a __len__ function to the block.
I found it annoying not to be able to do len(block). 
It is not revolutionary so if you do not like you can also not merge it.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1558537230.zip)

added len of a block

---

metatensor-core/cmake/version-defines.cmake
metatensor-torch/CMakeLists.txt

Previously the timestamp of `metatensor/torch/version.h` would change on every cmake re-configure, causing a full rebuild of the code. 
I tested this by running `cmake . && make` multiple times. Before this change all tests where recompiled, after this nothing gets recompiled.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1552518698.zip)

Do not rebuild C++ code if nothing changed

---

.github/workflows/coverage.yml
.github/workflows/docs.yml
.github/workflows/python-tests.yml
tox.ini

This way it will work automatically regardless of the version installed locally
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1566011521.zip)

Pin tox version in tox.ini

---

python/metatensor-operations/metatensor/operations/_dispatch.py
python/metatensor-torch/tests/operations/sort.py

fix #642
Fix the bug with `metatensor.torch.sort` #642.
The algorithm is not very smart but is constricted by `TorchScript`.
I also added the test to the torch part
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1589839581.zip)

fix the bug with `metatensor.torch.sort`

---

metatensor-core/CMakeLists.txt

Rustc now includes `/defaultlib:msvcrt` in the `native-static-lib` output, but with our setup CMake interpret this as a library to link and not a linker flag. Since we are already linking to msvcrt anyway, I just remove this from the list of libraries we pass to CMake.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1607891242.zip)

Try to fix windows build on CI

---

.github/workflows/build-wheels.yml

They are deprecated
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1620075969.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1620144767.zip)

Remove usage of macos-11 runner on Github Actions

---

python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py

Fixes a small bug: the device wasn't chosen properly for the strain in the ASE calculator. The strain was also called "scaling", I've renamed it to strain for consistency within our codes
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1623842506.zip)

Fix strain device in ASE calculator

---

.github/workflows/python-tests.yml
CONTRIBUTING.rst
metatensor-core/CHANGELOG.md
metatensor-torch/CHANGELOG.md
pyproject.toml
python/metatensor-core/pyproject.toml
python/metatensor-learn/CHANGELOG.md
python/metatensor-learn/pyproject.toml
python/metatensor-operations/CHANGELOG.md
python/metatensor-operations/pyproject.toml
python/metatensor-torch/pyproject.toml

I need a feature from 3.9 in #479, and 3.8 will be EOL in a couple of months. Most of the scientific Python ecosystem also already dropped both 3.8 and 3.9, so we are not dropping faster than our own dependencies.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1659856596.zip)

Drop support for Python 3.8, require 3.9

---

python/metatensor-operations/metatensor/operations/_dispatch.py
python/metatensor-operations/metatensor/operations/block_from_array.py
python/metatensor-operations/tests/_gradcheck.py
python/metatensor-operations/tests/add.py
python/metatensor-operations/tests/block_from_array.py

This PR adds utilities for doing finite difference tests for the metatensor-operations and uses them in the simple example of the `add` operation.
This is the first PR addressing issue https://github.com/lab-cosmo/metatensor/issues/84
The idea of the testing utilities originates from issue https://github.com/lab-cosmo/metatensor/issues/469
In the next run on this PR I want to dispatch the testing utilities so they can also be used for torch, but before that I would like to have some general feedback if this is going in a good direction.
----
📚 Documentation preview 📚: https://metatensor--479.org.readthedocs.build/en/479/
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1663450013.zip)

`metatensor-operations` finite difference test for add

---

metatensor-core/Cargo.toml
python/metatensor-core/tests/serialization.py

This does not change file saving, we are still only using STORED in this case.
Fix #469.
This is mainly intended to remove the surprising behavior as seen in the issue, where a file that should be loaded can only be loaded through numpy and not metatensor-core. Such files should be rare, since one has to go out of their way to create it (saving with metatensor/numpy, then loading as a normal npz and re-saving with different settings).
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1663633276.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1664257799.zip)

Allow loading npz files which use DEFLATE compression

---

python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py

When converting the stress in the ASE calculator, we're using `np.transpose` on a list of floats, but that does nothing and it just converts the list to an array.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1670552491.zip)

Do not use transpose in ASE calculator

---

python/metatensor-torch/metatensor/torch/atomistic/documentation.py

The documentation at https://docs.metatensor.org/latest/atomistic/reference/models/metadata.html
says there is a `ModelMetadata.print()` method, but it doesn't work at the moment because it's not registered
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1672240911.zip)

Fix documentation for printing `ModelMetadata`

---

python/metatensor-torch/metatensor/torch/_c_lib.py
rust/metatensor-sys/Cargo.toml

See #665 for one example of this, the same happens on TODI (CSCS super computer) when using the NVIDIA provided container.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1678291919.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1678385834.zip)

Better error message in case of mismatch torch between build and run time

---

python/metatensor-core/metatensor/block.py
python/metatensor-core/metatensor/data/array.py

ctypes.py_object(obj) does NOT give us the Py_Object* corresponding to `obj`, but a wrapper that keeps it's own reference to `obj`. Multiple calls give us different wrapper, meaning our manual Py_IncRef/Py_DecRef where acting on different wrappers and keeping `obj` alive.
This only affects metatensor-core in Python, and was found & reported by @ppegolo. Below is a script that shows the leak:
```py
import resource
import numpy as np
import torch
from metatensor import Labels, TensorBlock, TensorMap
class Model(torch.nn.Module):
def __init__(self, size):
super().__init__()
self.model = torch.nn.Sequential(torch.nn.Linear(size, size))
def forward(self, features):
blocks = []
for feat in features.blocks():
blocks.append(
TensorBlock(
values=self.model(feat.values),
samples=feat.samples, …
```

Stop leaking memory for values stored inside blocks

---

metatensor-torch/src/atomistic/system.cpp

PyTorch **sometimes** does not free the corresponding data when dropping the computational graph, leaking the corresponding memory. I don't quite understand when or why this happen, a basic example with a single node in the computational graph does not suffer from the same issue.
This was causing memory leaks when running MD simulations (I found this while debugging something unrelated in the LAMMPS interface).
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1687033155.zip)

Do not use `ctx->saved_data` in autograd

---

pyproject.toml
tox.ini

Manage pytest warnings inside the  `pyproject.toml` instead of list of command line flags inside the `tox.ini`

Use pyproject.toml for manage pytest warnings

---

docs/src/atomistic/outputs.rst
metatensor-torch/src/atomistic/model.cpp
python/metatensor-torch/metatensor/torch/atomistic/outputs.py
python/metatensor-torch/tests/atomistic/model.py
python/metatensor-torch/tests/atomistic/outputs.py

This PR implements ensembles of energies as a new standard output for atomistic models (#650). It also makes the necessary changes to the ASE calculator to make this property (which is not standard in ASE) available to the user. In addition, the dipole is also registered as a new property and added to the ASE calculator
TODO: actual conversion factors for dipoles
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1719201793.zip)

Add `energy_ensemble` as a new standard output for atomistic models

---

python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py

These changes allow for a user to calculate and store non-standard properties in the ASE calculator. For relatively experienced users, this is also a fix for #655 (one can set `"energy", "forces", "stress"` as `properties_to_store`, these will be calculated at each step, and then the inherited `get_property` function will not re-trigger a calculation but just read from the `calc.results` dict).
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1723565709.zip)

Store additional properties in ASE calculator

---

python/examples/atomistic/1-export-atomistic-model.py
python/examples/atomistic/2-running-ase-md.py
python/examples/atomistic/3-profiling.py
python/metatensor-torch/metatensor/torch/atomistic/documentation.py
python/metatensor-torch/metatensor/torch/documentation.py

In the atomistic example, we currently return an empty dictionary (`{}`) if the output key does not match the supported keys of a model. I believe this approach is not ideal because the keys of the returned dictionary from a model should match what is requested by the user/engine. This concept is often referred to as _type consistency_ or _type fidelity_.
For example, if the engine requests the keys "energy" and "other_energy", the model should return a dictionary containing these keys or raise an error.
If the model is part of a larger model, the larger model can handle the branching based on the output keys.
I can also add the explanation above as a comment in the code and/or the docs if we think it may be helpful.
Additionally, I fixed broken links to the TensorBlock.dtype attribute.
- …

Minor improvements to atomistic examples and documentation

---

python/metatensor-operations/metatensor/operations/split.py

In `rst` is not supported to put any character other than a space after closing a markup. But, we have something like this in docstring of the split method
```rst
:py:class:`TensorMap`s
```
The produced rendering is not as expected
I changed the sentence so that the paragraph looks like this
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1759673529.zip)

Fix render issue in split docs

---

python/metatensor-torch/metatensor/torch/atomistic/model.py
python/metatensor-torch/tests/atomistic/ase_calculator.py
python/metatensor-torch/tests/atomistic/model.py

This feature would be very useful to access information about the underlying model
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1760815821.zip)

Allow to access `wrapped_module` of exported models

---

metatensor-torch/CHANGELOG.md
metatensor-torch/include/metatensor/torch/atomistic/model.hpp
metatensor-torch/src/atomistic/model.cpp
metatensor-torch/src/register.cpp
metatensor-torch/tests/atomistic.cpp
python/metatensor-torch/metatensor/torch/atomistic/documentation.py
python/metatensor-torch/tests/atomistic/metadata.py

As in the title.
Should we print this extra metadata with the other metadata or not?
Should we implement a getter? (The other fields don't have it though)
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1766765529.zip)

Allow for extra metadata in atomistic models

---

.github/workflows/build-wheels.yml
python/metatensor-torch/setup.py
scripts/create-torch-versions-range.py

As it says on the tin! PyTorch 2.3.1 should have fixed the previous issue on Windows.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1815147920.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1815206759.zip)

Re-enabled builds for PyTorch 2.3 and 2.4 on Windows

---

.github/workflows/rust-tests.yml
metatensor-core/CMakeLists.txt
metatensor-core/tests/check-cxx-install.rs
metatensor-core/tests/cmake-project/CMakeLists.txt
metatensor-core/tests/cpp/CMakeLists.txt

The MinGW job was also using MSVC compiler by mistake
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1815307315.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1686235583.zip)

Actually use MinGW on CI

---

docs/src/core/reference/c/labels.rst
julia/src/generated/_c_api.jl
metatensor-core/CHANGELOG.md
metatensor-core/include/metatensor.h
metatensor-core/include/metatensor.hpp
metatensor-core/src/c_api/labels.rs
metatensor-core/src/labels.rs
metatensor-core/tests/cpp/labels.cpp
metatensor-torch/CHANGELOG.md
metatensor-torch/include/metatensor/torch/labels.hpp
metatensor-torch/src/labels.cpp
metatensor-torch/src/register.cpp
python/metatensor-core/metatensor/_c_api.py
python/metatensor-core/metatensor/labels.py
python/metatensor-core/tests/labels.py
python/metatensor-operations/metatensor/operations/drop_blocks.py
python/metatensor-operations/metatensor/operations/slice.py
python/metatensor-operations/tests/drop_blocks.py
python/metatensor-torch/metatensor/torch/documentation.py
python/metatensor-torch/tests/labels.py
rust/metatensor-sys/src/c_api.rs
rust/metatensor/src/labels.rs

This function enables the selection of a subset of entries in Labels using another Labels to define the selection. Mulitple entries in the selection are interpreted as an `or` operation.
Fix #97 
Fix #700 as well, bringing the time for `slice_block` in the issue example to ~380ms, very similar to the manual implementation.
Still TBD: 
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1811714225.zip)

Implement Labels selection

---

docs/extensions/versions_list.py
docs/src/atomistic/reference/index.rst
docs/src/conf.py
docs/src/core/reference/c/index.rst
docs/src/core/reference/cxx/index.rst
docs/src/core/reference/python/index.rst
docs/src/learn/reference/index.rst
docs/src/operations/reference/index.rst
docs/src/torch/reference/index.rst
docs/static/css/metatensor.css
metatensor-core/include/metatensor.hpp
tox.ini

This changes the extension we use for linking to previous versions of the documentation, making the source code and rendered version cleaner.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1861291718.zip)

Improve the version list in docs

---

docs/src/atomistic/outputs.rst
metatensor-torch/src/atomistic/model.cpp
python/metatensor-torch/metatensor/torch/atomistic/outputs.py
python/metatensor-torch/tests/atomistic/outputs.py

Added a new standard output "features" to return the internal or learned features from a model (model's intermediate values before final predictions). The output format checks were taken from the Plumed [doc](https://www.plumed.org/doc-master/user-doc/html/_m_e_t_a_t_e_n_s_o_r.html).
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1874675914.zip)

Features standard output

---

.github/workflows/build-wheels.yml

The wheels for metatensor-torch v0.5.4 contain wrong metadata: they all declare requiring a single specific version of torch when they are actually compatible with any (supported) version. This is because our script to edit the metadata failed (the matched string changed from `torch ==2.2.*` to `torch==2.2.*`). This should fix it and account for both cases.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1882716057.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1882935007.zip)

Fix metadata in merged metatensor-torch wheels

---

python/metatensor-core/CMakeLists.txt
python/metatensor-core/MANIFEST.in
python/metatensor-core/metatensor/_c_lib.py
python/metatensor-core/metatensor/utils.py
python/metatensor-core/setup.py
python/metatensor-torch/CMakeLists.txt
python/metatensor-torch/MANIFEST.in
python/metatensor-torch/metatensor/torch/_c_lib.py
python/metatensor-torch/metatensor/torch/utils.py
python/metatensor-torch/setup.py

This should be everything that need to change on the code side for #402.
The main change is that the `metatensor-core` and `metatensor-torch` python packages now have their own CMakeFile.txt that handles either finding a pre-existing shared library or building one from scratch.
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/1895733445.zip)

Use externally-provided shared libraries in Python

---

rust/metatensor/CHANGELOG.md
rust/metatensor/Cargo.toml

This brings the changes in `-core` v0.1.10 to Rust.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/1915633664.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/1915769273.zip)

Release metatensor-rust v0.1.6

---

.github/workflows/rust-tests.yml
CONTRIBUTING.rst
metatensor-core/CHANGELOG.md
metatensor-core/Cargo.toml
metatensor-core/build.rs
metatensor-core/include/metatensor.h
metatensor-torch/Cargo.toml
python/Cargo.toml
python/metatensor-torch/tests/atomistic/metadata.py
python/metatensor-torch/tests/serialization.py
rust/metatensor-sys/Cargo.toml
rust/metatensor/Cargo.toml
rust/metatensor/src/lib.rs

This was prompted by a test failure in https://github.com/Luthaf/rascaline/pull/328. This allows us to update a bunch of dependencies to newer versions.
The version of rustc available through APT is 1.75 for ubuntu from 20.04 to 24.04, so this should not change anything for people using rustc from there.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/1971205940.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/1971339516.zip)

Bump minimal Rust version to 1.74

---

python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
python/metatensor-torch/tests/atomistic/ase_calculator.py

This enable the simultaneous calculation of multiple properties during an MD run. The main caveat is that the `additional_outputs` will be computed at every step, even if they would not be needed. One of the main use case is thus to compute things one would need at every step anyway, such as uncertainty estimate on the energy.

Allow to request `additional_outputs` in ASE calculator

---

metatensor-torch/CHANGELOG.md
metatensor-torch/include/metatensor/torch/atomistic/system.hpp
metatensor-torch/src/atomistic/system.cpp
metatensor-torch/src/register.cpp
python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
python/metatensor-torch/metatensor/torch/atomistic/model.py
python/metatensor-torch/metatensor/torch/atomistic/systems_to_torch.py
python/metatensor-torch/tests/atomistic/ase_calculator.py
python/metatensor-torch/tests/atomistic/examples.py
python/metatensor-torch/tests/atomistic/neighbors.py
python/metatensor-torch/tests/atomistic/outputs.py
python/metatensor-torch/tests/atomistic/systems.py

This PR implements PBCs in the `System` class, allowing for structures where only some of the dimensions have PBCs.
A few questions:
- should we have default arguments (most likely `True, True, True` for backward compatibility)?
- is the strategy to ignore the cell if the PBCs are False? Or do we require it to have some all-zero rows if PBCs are False?
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2004641647.zip)

Add PBCs to the `System` class

---

.github/workflows/build-wheels.yml

Creating the release failed for `metatensor-operation-v0.2.4`: https://github.com/metatensor/metatensor/actions/runs/11295315675/job/31419476194
I'm not sure this can be tested before the next release.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2074398763.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2074567310.zip)

Add the right permissions to CI making the releases

---

metatensor-core/src/blocks.rs
metatensor-core/src/c_api/labels.rs
metatensor-core/src/io/labels.rs
metatensor-core/src/labels.rs
metatensor-core/src/lib.rs
metatensor-core/src/tensor/keys_to_properties.rs
metatensor-core/src/tensor/keys_to_samples.rs
metatensor-core/src/tensor/mod.rs
metatensor-core/src/tensor/utils.rs
python/metatensor-core/metatensor/labels.py
python/metatensor-operations/metatensor/operations/manipulate_dimension.py
python/metatensor-operations/tests/manipulate_dimension.py
python/metatensor-torch/metatensor/torch/documentation.py
rust/metatensor/src/labels.rs

This removes some extra cost, in particular when createing very large Labels that are only here to hold data (this is mostly going to be sample Labels), and which are never searched for the presence/absence of a given entry.
This is a follow up to #752, and related to #751
TODO:
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2088701875.zip)

Lazily initialize the `positions` HashMap in Labels

---

python/metatensor-operations/CHANGELOG.md
python/metatensor-operations/metatensor/operations/manipulate_dimension.py
python/metatensor-operations/tests/manipulate_dimension.py

Fixes #520. It allows passing `axis="components"` to `metatensor.operations.rename_dimension`.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2098956332.zip)

Allow TensorBlock components renaming

---

tox.ini

- do not pass PYTHONPATH to tox
- set PIP_EXTRA_INDEX_URL to use CPU-only version of torch when building docs
Both issues found by @HannaTuerk, thanks!
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2099060993.zip)

Tox improvements

---

metatensor-torch/CHANGELOG.md
python/metatensor-torch/metatensor/torch/atomistic/__init__.py
python/metatensor-torch/metatensor/torch/atomistic/model.py
python/metatensor-torch/tests/atomistic/model.py

Fixes #697
As stated in the title this adds a simple function to check if a loaded module is a good or a bad `torch.nn.Module`.
I need this for https://github.com/metatensor/metatrain/pull/352
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2099655165.zip)

Add `is_atomistic_model` function

---

python/metatensor-torch/metatensor/torch/atomistic/model.py
python/metatensor-torch/tests/atomistic/model.py

This fixes #630.
Added simple checking routines within the save function to look for the units, and to raise a warning when the string is empty.
EDIT: took inspiration from the export function of metatrain as suggested by @Luthaf.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2098928048.zip)

add unit check and warning when saving

---

python/metatensor-learn/tests/_tests_utils.py
python/metatensor-operations/CHANGELOG.md
python/metatensor-operations/metatensor/operations/_backend.py
python/metatensor-operations/metatensor/operations/slice.py
python/metatensor-operations/metatensor/operations/split.py
python/metatensor-operations/tests/join.py
python/metatensor-operations/tests/slice.py
python/metatensor-operations/tests/split.py
python/metatensor-operations/tests/unique_metadata.py
python/metatensor-torch/metatensor/torch/operations.py
python/metatensor-torch/tests/operations/slice.py
python/metatensor-torch/tests/operations/split.py

Fixes #187. One pain point for me in using mts is when I know that I want to pick a slice of a block, I know what indices I need, and instead I've to figure out how to do the same thing by sample labels. This PR (that looks like could be pretty simple) implement direct selection by indices.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2112623199.zip)

split blocks (and maps) by index as well as by label

---

python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
python/metatensor-torch/setup.py
python/metatensor-torch/tests/atomistic/neighbors.py
tox.ini

Makes `vesin` a dependency to make sure it is used when running MD with ASE or i-PI.
This can provide a huge speed boost (up to 15x) for fast models.
~~- [ ] Tests updated (for new features and bugfixes)?~~
~~- [ ] Issue referenced (for PRs that solve an issue)?~~
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2113196843.zip)
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2113010210.zip)

Make `vesin` a dependency of `metatensor-torch`

---

python/metatensor-core/tests/data.py
python/metatensor-learn/metatensor/learn/_backend.py
python/metatensor-learn/metatensor/learn/nn/sequential.py
python/metatensor-operations/metatensor/operations/_backend.py
python/metatensor-operations/metatensor/operations/_dispatch.py
python/metatensor-operations/metatensor/operations/add.py
python/metatensor-operations/metatensor/operations/divide.py
python/metatensor-operations/metatensor/operations/drop_blocks.py
python/metatensor-operations/metatensor/operations/equal_metadata.py
python/metatensor-operations/metatensor/operations/join.py
python/metatensor-operations/metatensor/operations/multiply.py
python/metatensor-operations/metatensor/operations/pow.py
python/metatensor-operations/metatensor/operations/reduce_over_samples.py
python/metatensor-operations/metatensor/operations/slice.py
python/metatensor-operations/metatensor/operations/split.py
python/metatensor-operations/metatensor/operations/subtract.py
python/metatensor-operations/metatensor/operations/unique_metadata.py
python/metatensor-torch/metatensor/torch/atomistic/systems_to_torch.py
python/metatensor-torch/metatensor/torch/learn.py
python/metatensor-torch/metatensor/torch/operations.py
python/metatensor-torch/tests/atomistic/model.py
python/metatensor-torch/tests/atomistic/systems_to_torch.py
python/metatensor-torch/tests/operations/add.py

We can not warn the other way around, since the TorchScript Python runtime will try to do a cast before we even get to our own code.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2113032313.zip)

Warn when using types from `-torch` with operations from `-core`

---

metatensor-torch/include/metatensor/torch/atomistic/system.hpp
metatensor-torch/src/atomistic/system.cpp
metatensor-torch/src/register.cpp
metatensor-torch/tests/atomistic.cpp
metatensor-torch/tests/neighbor-checks/README.md
python/examples/atomistic/3-atomistic-model-with-nl.py
python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
python/metatensor-torch/metatensor/torch/atomistic/documentation.py
python/metatensor-torch/tests/atomistic/ase_calculator.py
python/metatensor-torch/tests/atomistic/model.py
python/metatensor-torch/tests/atomistic/neighbors.py
python/metatensor-torch/tests/atomistic/systems.py
tox.ini

Adds a flag to the neighbor list classes to signal whether the neighbor list is "strict" - that is if it guarantees not to pass atoms beyond the cutoff. 
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2116989539.zip)

Added an option for strict neighbor list

---

pyproject.toml
python/metatensor-core/metatensor/labels.py
python/metatensor-learn/metatensor/learn/data/dataset.py
python/metatensor-learn/metatensor/learn/nn/module_map.py
python/metatensor-operations/metatensor/operations/_checks.py
python/metatensor-operations/metatensor/operations/manipulate_dimension.py
python/metatensor-torch/metatensor/torch/atomistic/model.py
python/metatensor-torch/metatensor/torch/documentation.py
tox.ini

This is a follow-up to #747, also replacing `blackdoc` with ruff.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2145915030.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2146066398.zip)

Use ruff instead of blackdoc to format examples in docstrings

---

metatensor-torch/src/atomistic/system.cpp
metatensor-torch/tests/atomistic.cpp
python/metatensor-torch/tests/atomistic/model.py

This is used among other by rascaline to know which NL it requested and convert them to the internal format. It looks like I forgot to add serialization for these, meaning that the models using rascaline would only re-use NL when running in pure Python mode, and not through TorchScript. In the other cases, rascaline would recompute the NL, hiding the issue, until someone tried to run the model in LAMMPS where we can not recompute the NL.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2147405572.zip)

Make sure to serialize NeighborListOptions.requestors

---

python/metatensor-learn/metatensor/learn/data/dataset.py

It was accidentally O(n), since it was checking whether the index was in bounds by checking if it was in a list (with `idx not in list`), which uses a linear scan. Since all indexes are contiguous anyway, this is replaced by `idx < 0 and idx >= len(self)`.
Fix #788, thanks @frostedoyster for the detailed reproduction, it really helped identifying the issue!
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2170635027.zip)

Make dataset indexing O(1)

---

metatensor-torch/src/labels.cpp
python/metatensor-core/tests/labels.py
python/metatensor-torch/tests/labels.py

The torch code would previously fail with `invalid parameter: got invalid NULL pointer for selected at metatensor-core/src/c_api/labels.rs:556`
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2177989480.zip)

Do not crash when selecting from an empty set of Labels

---

python/metatensor-torch/metatensor/torch/documentation.py

They were missing the new `TensorBlock` functionality
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2208028267.zip)

Update docs for `save` and `save_buffer`

---

.github/workflows/build-wheels.yml
.github/workflows/rust-tests.yml
python/metatensor_core/CMakeLists.txt
python/metatensor_torch/CMakeLists.txt

An unwanted change was included in release 0.6.1 of metatensor-torch, related to the code that enables building Python wheels against an already existing libmetatensor/libmetatensor-torch. These are intended to be used for the conda release (cf #402 and #729), and where not tested before.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2284266379.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2295095845.zip)

Fix external build, and add CI job to check them

---

docs/src/torch/reference/cxx/block.rst
docs/src/torch/reference/cxx/labels.rst
docs/src/torch/reference/cxx/miscellaneous.rst
docs/src/torch/reference/cxx/tensor.rst
metatensor-torch/CHANGELOG.md
metatensor-torch/include/metatensor/torch/atomistic/model.hpp
metatensor-torch/include/metatensor/torch/atomistic/system.hpp
metatensor-torch/include/metatensor/torch/block.hpp
metatensor-torch/include/metatensor/torch/labels.hpp
metatensor-torch/include/metatensor/torch/misc.hpp
metatensor-torch/include/metatensor/torch/tensor.hpp
metatensor-torch/src/atomistic/model.cpp
metatensor-torch/src/atomistic/system.cpp
metatensor-torch/src/block.cpp
metatensor-torch/src/labels.cpp
metatensor-torch/src/misc.cpp
metatensor-torch/src/register.cpp
metatensor-torch/src/tensor.cpp
metatensor-torch/tests/block.cpp
metatensor-torch/tests/tensor.cpp

If users need to differentiate between these and the ones in `metatensor::` namespace, they should use the namespace explicitly
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2446377848.zip)

Remove Torch prefix for types in `metatensor_torch::` namespace

---

python/metatensor_core/pyproject.toml
python/metatensor_core/setup.py
python/metatensor_torch/pyproject.toml
python/metatensor_torch/setup.py

Building the code gave this warning:
```
********************************************************************************
Ensure that any custom bdist_wheel implementation is a subclass of
setuptools.command.bdist_wheel.bdist_wheel.
By 2025-Oct-15, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://github.com/pypa/wheel/pull/631 for details.
********************************************************************************
```

Use bdist_wheel from setuptools, the one in wheel is deprecated

---

.github/workflows/build-wheels.yml
.github/workflows/docs.yml

This should fix CI here until the issue is resolved upstream!

Disable `PicoCentauri/comment-artifact@v1` when running from forks

---

.github/workflows/build-wheels.yml

These runners are [now available](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/) for OSS projects, and should be a lot faster than using QEMU for emulation.
- `metatensor-core` wheel now takes 2min instead of 9min30s
- `metatensor-torch` wheel now takes 3min instead of 25min!
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2456690745.zip)
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2456722196.zip)
[⚙️ Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2456951962.zip)

Build linux-arm wheels on native ARM runners

---

python/metatensor_core/metatensor/block.py
python/metatensor_core/metatensor/data/__init__.py
python/metatensor_core/metatensor/data/array.py
python/metatensor_core/metatensor/data/extract.py
python/metatensor_core/metatensor/io/_block.py
python/metatensor_core/metatensor/labels.py
python/metatensor_core/setup.py
python/metatensor_core/tests/data.py

Triggered by #818 
Using the script in the issue, on main:
```
numpy-cpu l_max=10: sphericart is 0.59ms, sphericart.metatensor is 2.04ms
```
With this PR:
```
numpy-cpu l_max=10: sphericart is 0.61ms, sphericart.metatensor is 1.55ms
```
There are still a lot more improvement to add, but these are the one I found with line_profiler.
The current profile is 
```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
81                                               @profile
82                                               def compute_with_gradients(self, xyz: TensorMap) -> TensorMap:
83                                                   """
84                                                   Computes the spherical …
```

Small improvements to the speed of metatensor-core Python bindings

---

tox.ini

Otherwise `virtualenv` might re-use an old installation and fail the build down the line.

Make sure a recent-enough version of setuptools is installed by tox

---

python/metatensor_torch/CMakeLists.txt

This makes sure that code consuming a `metatensor_torch` installation from PyPI will be able to find metatensor and torch.(i.e. https://github.com/metatensor/metatomic/pull/1)

Use $ORIGIN/@loader_path in metatensor_torch install rpath

---

metatensor-core/include/metatensor.h
metatensor-core/src/c_api/labels.rs

Just changed a copy-paste error in the c_api, it should be 'intersection' for the intersection function not 'union'
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2547101893.zip)

Fixed copy paste error in intersection function description

---

docs/src/core/reference/c/index.rst
docs/src/core/reference/cxx/index.rst
docs/src/core/reference/python/index.rst
metatensor-core/CHANGELOG.md
metatensor-core/Cargo.toml
metatensor-core/tests/cmake-project/CMakeLists.txt
metatensor-torch/CMakeLists.txt
python/metatensor_core/CMakeLists.txt
rust/metatensor-sys/Cargo.toml

Changed the default extension for file serialization is now `.mts` instead of `.npz`. This change is backward compatible since `npz`/`mts` is basically a ZIP folder. 
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2603991978.zip)
[⚙️ Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2604211512.zip)

Release metatensor-core v0.1.12

---

docs/src/operations/reference/index.rst
python/metatensor_operations/CHANGELOG.md
python/metatensor_operations/setup.py

This release fixes a severe bug in `mean_over_samples`.
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2607315262.zip)
[⚙️ Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2607379241.zip)

Release metatensor-operations v0.3.2

---

python/metatensor_torch/metatensor/torch/atomistic/ase_calculator.py

As in the title, otherwise the stress is +inf or -inf, and warnings are displayed when we convert those to Voigt stresses
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2615423377.zip)

Only calculate stress if PBCs are there

---

.github/workflows/build-wheels.yml

Bumped the version in the build-wheels action to be consistent with all other Python versions
This change does not affect the actual build process of the wheels! Each wheel is run in an independent docker container set up by `cibuildwheel`.
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2609044419.zip)
[⚙️ Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2609149930.zip)

Bump backend Python version when building wheels

---

metatensor-core/Cargo.toml
metatensor-core/src/blocks.rs
metatensor-core/src/labels.rs
python/metatensor_core/tests/blocks.py
rust/metatensor/src/labels.rs

This is a follow up to #820, addressing #818; but this time modifying the underlying Rust code to give everyone the same speed up. The biggest change is adding the `is_lexicographically_sorted` flag discussed in #142 (for now only as an internal flag, we can expose it as part of the public API later), and using it to make gradient sample checks a lot faster. 
With this, I get the following profile on the script from #818:
```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
79                                               @profile
80                                               def compute_with_gradients(self, xyz: TensorMap) -> TensorMap:
81                                                   """
82 …
```

Some more speed improvement in metatensor-core library

---

python/metatensor_operations/metatensor/operations/filter_blocks.py
python/metatensor_operations/tests/filter_blocks.py

This ensures that when all the filtering `keys` are present in the `tensor` to be filtered, the resulting `TensorMap` has keys whose order matches those in the `keys` passed to `filter_blocks`
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2859051658.zip)

Maintain the order of the filtering keys in `filter_blocks`

---

python/metatensor_torch/metatensor/torch/atomistic/model.py
python/metatensor_torch/tests/atomistic/model.py

On a structure of 250 atoms, this saves 0.5 ms
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2874057859.zip)

Improve speed of atomic type check

---

python/metatensor_torch/metatensor/torch/atomistic/model.py

Follow up to #886, otherwise the dtype of both array could not match in some cases, and I would get this error:
```
RuntimeError: Expected elements.dtype() == test_elements.dtype() to be true, but got false.
```

Make sure `supported_types` has the same dtype as `all_types`

---

metatensor-torch/src/atomistic/model.cpp
metatensor-torch/tests/atomistic.cpp

The units for `forces` should be `force`, not `forces`, and the units for `stress` should be `pressure`, not `stress`
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2917764374.zip)

Fix units for forces and stresses

---

pyproject.toml
python/metatensor_core/pyproject.toml
python/metatensor_learn/pyproject.toml
python/metatensor_operations/pyproject.toml
python/metatensor_torch/pyproject.toml
tox.ini

Setuptools is starting to warn about the old syntax being deprecated

Use SPDX license indentifiers in pyproject.toml

---

metatensor-core/cmake/metatensor-config.in.cmake

Otherwise it prevent cmake from using `find_package(metatensor)` in mulitple scopes
This is required for https://github.com/metatensor/metatomic/pull/1

Do not make the imported targets global

---

metatensor-core/src/blocks.rs
metatensor-core/src/c_api/labels.rs
metatensor-core/src/io/labels.rs
metatensor-core/src/labels.rs
metatensor-core/src/tensor/mod.rs

`Labels::new` used to take `Vec<impl Into<LabelsValue>>` for convenience, assuming that in the case where data was already LabelsValue the allocation would be skipped. This is not the case, so I changed it and added a separate convenience function for the tests.
This cuts 160us out of 740us in an example building neighbor lists sample labels

Do no re-allocate Labels values upon construction

---

.github/workflows/build-wheels.yml
.github/workflows/python-tests.yml
.github/workflows/torch-tests.yml
python/scripts/rustc-manylinux2014_aarch64/Dockerfile
python/scripts/rustc-manylinux2014_x86_64/Dockerfile
python/scripts/rustc-manylinux_2_28_aarch64/Dockerfile
python/scripts/rustc-manylinux_2_28_x86_64/Dockerfile
tox.ini

The biggest change is that we will now have manylinux_2_28 wheels instead of manylinux2014 wheels. These should still be compatible with most linux distributions used nowadays.

Add support for Torch 2.7

---

docs/src/learn/reference/index.rst
docs/src/operations/reference/index.rst
python/metatensor_learn/CHANGELOG.md
python/metatensor_learn/setup.py
python/metatensor_operations/CHANGELOG.md
python/metatensor_operations/setup.py

We need a new release to be compatible with metatensor-torch v0.7.6 due to #906

Release metatensor-operations v0.3.3 and metatensor-learn v0.3.2

---

python/metatensor_core/setup.py
python/metatensor_torch/setup.py
python/scripts/rustc-manylinux_2_28_aarch64/Dockerfile
python/scripts/rustc-manylinux_2_28_x86_64/Dockerfile

I need this now to debug why `libmetatensor_torch.so` contains its own copy of `__cxa_call_terminate` while metatomic-torch does not, but it will also be useful long term if someone has issues building the wheels.

Enable verbose output when building wheels

---

python/metatensor_core/metatensor/io/_utils.py
python/metatensor_core/tests/serialization.py

The size of the memoryview was wrong, which prevented re-loading a buffer from memory

Fix serialization to buffer in metatensor-core

---

metatensor-torch/src/labels.cpp
python/metatensor_core/tests/labels.py
python/metatensor_torch/tests/labels.py

Using an out of bound index in `Labels.insert` with `metatensor.torch` leads to a segmentation fault. This PR adds a bound check to `LabelsHolder::insert` to get a similar error to the one obtained with `metatensor`.

Prevent segmentation fault for out-of-bound index in Labels.insert

---

python/metatensor_operations/metatensor/operations/_manipulate_dimension.py
python/metatensor_torch/tests/operations/manipulate_dimension.py
scripts/git-version-info.py

Close #600.
This PR adds a check that arrays are non-empty before dispatching to concatenate. Otherwise, returns an empty tensor with the same type as values.

Handle empty vector before dispatchiong to concatenate when inserting a Label dimension

---

metatensor-core/cmake/metatensor-config.in.cmake
metatensor-torch/cmake/metatensor_torch-config.in.cmake
metatensor-torch/tests/utils/mod.rs

This should make it easier to debug downstream users pulling the wrong version.

Print where metatensor(-torch) was found when using find_package in CMake

---

.codecov.yml
.github/workflows/coverage.yml
.gitignore
CONTRIBUTING.rst

Partially implements #368. Didn't use the older Tarpaulin approach from `rascaline` because this instrumenting the source instead of sampling is better supported and more stable. Plus [cargo-llvm-cov](https://github.com/taiki-e/cargo-llvm-cov) also supports regions in codecov.
Locally I am testing this via:
```bash
rustup component add llvm-tools 
cargo +stable install cargo-llvm-cov --locked
cargo llvm-cov --all-features --workspace --no-fail-fast --codecov --output-path rust_codecov.json --exclude metatensor-python
```
The more traditional route also works:
```bash
CARGO_INCREMENTAL=0 RUSTFLAGS='-Cinstrument-coverage' LLVM_PROFILE_FILE='cargo-test-%p-%m.profraw' cargo test
grcov . --binary-path ./target/debug/deps/ -s . -t html --branch --ignore-not-existing --ignore '../*' --ignore …
```

[ENH] Add rust coverage

---

.github/workflows/build-wheels.yml
python/metatensor_core/setup.py

I flipped the default for metatensor-core to `debug` in setup.py in #820 for debugging, and forgot to change it back. 
So we now have two layers of protection: the default build type from Python is now back to `release`, and we force it to be `release` when building wheels in CI.
Not sure if there is something else we could do to improve the situation. It seems that detecting whether a given binary was built in release or debug mode is non trivial.

Make sure to always build wheels in release mode

---

docs/src/operations/reference/manipulation/drop-blocks.rst
python/metatensor_operations/metatensor/operations/__init__.py
python/metatensor_operations/metatensor/operations/_drop_blocks.py
python/metatensor_operations/tests/drop_blocks.py
python/metatensor_torch/tests/operations/drop_blocks.py

In this case, a method called drop_empty_blocks has been implemented, whose function is to drop all blocks contained in a TensorMap that have any of their dimensions equal to 0.
fix #786

Add `drop_empty_blocks` operation
