metatensor/metatensor

.github/workflows/tests.yml, aml_storage/_c_api.py, aml_storage/block.py, aml_storage/data.py, aml_storage/descriptor.py, aml_storage/labels.py, aml_storage/status.py, include/aml_storage.h, pyproject.toml, src/c_api/blocks.rs, src/c_api/descriptor.rs, src/c_api/labels.rs, tests/python/blocks.py, tests/python/data.py, tests/python/descriptors.py, tests/python/labels.py, tests/python/utils.py
@ceriottm the second commit implements the ability to do lookup by hash inside labels owned by the Rust side
=> Labels API improvements in Python

aml_storage/_c_api.py, aml_storage/data.py, aml_storage/descriptor.py, include/aml_storage.h, src/blocks.rs, src/c_api/blocks.rs, src/c_api/data.rs, src/c_api/descriptor.rs, src/c_api/mod.rs, src/data.rs, src/descriptor.rs, src/labels.rs
The first commit is a pre-requisite to be able to have different components for values & gradients
=> Allow to only move some selected variables from components to features

equistore/_c_api.py, equistore/tensor.py, include/equistore.h, src/c_api/tensor.rs, tests/python/tensor.py
Modified the TensorMap.block() function to allow returning multiple blocks matching selection criteria.
=> Multiple blocks selection  

setup.cfg, setup.py
Tiny change which saves some lines :-)
=> Move python version check to setup.cfg

.github/workflows/build-wheels.yml, .github/workflows/tests.yml
ubuntu-18.04 and macos-10.15 are deprecated
=> Update CI runners

src/tensor/keys_to_properties.rs, src/tensor/keys_to_samples.rs, src/tensor/utils.rs
The first commit fixes a bug found together with @PicoCentauri, the second commit a bug found by @hurricane642.
=> More fixes for keys_to_xxx

docs/src/reference/python/operations/empty_like.rst, docs/src/reference/python/operations/index.rst, docs/src/reference/python/operations/ones_like.rst, docs/src/reference/python/operations/zeros_like.rst, python/src/equistore/operations/__init__.py, python/src/equistore/operations/_dispatch.py, python/src/equistore/operations/_utils.py, python/src/equistore/operations/empty_like.py, python/src/equistore/operations/ones_like.py, python/src/equistore/operations/zeros_like.py, python/tests/operations/empty_like.py, python/tests/operations/ones_like.py, python/tests/operations/zeros_like.py
Add the function ``zeros`` and ``zeros_like``. 
The first takes the metadata as input and gives a ``TensorMap`` with values full of zeros.
The second takes a ``TensorMap``  and gives a ``TensorMap``  with the same metadata but the values matrices full zero.
Not sure how much these functions can be usefull
=> zeros and zeros_like

docs/src/reference/python/operations/add.rst, docs/src/reference/python/operations/index.rst, docs/src/reference/python/operations/multiply.rst, python/src/equistore/operations/__init__.py, python/src/equistore/operations/add.py, python/src/equistore/operations/multiply.py, python/tests/operations/add.py, python/tests/operations/multiply.py
A first draft of a sum function, so far it has no test.
it sums a TensorMap + a constant value/array or TensorMap + TensorMap. 
In the first case, the metadata of the result is the one of th; input TensorMap, in the second the two input TensorMaps must have the same metadata that will be the same as the input.
=> added add function

python/src/equistore/operations/_utils.py, python/src/equistore/operations/add.py, python/src/equistore/operations/allclose.py, python/src/equistore/operations/dot.py, python/src/equistore/operations/join.py, python/src/equistore/operations/lstsq.py, python/src/equistore/operations/multiply.py, python/src/equistore/operations/solve.py
The current check function for TensorMaps was only checking for keys and giving not clear error messages. I enhances this function by also checking that number of blocks (same as number of keys) is the same.
=> Enhance TensorMap check function

python/scripts/build-wheels/Dockerfile, src/io/mod.rs, src/labels.rs, src/lib.rs, src/tensor/mod.rs, src/utils.rs, tests/utils/mod.rs
This is a follow up to #111, trying to run on an older glibc/produce wheels compatible with more linux distributions.
=> Downgrade manylinux

docs/src/reference/python/operations/manipulation/index.rst, docs/src/reference/python/operations/manipulation/samples-reduction.rst, python/src/equistore/operations/__init__.py, python/src/equistore/operations/_dispatch.py, python/src/equistore/operations/reduce_over_samples.py, python/tests/operations/reduce_over_samples.py
I add this for the variance and the std over the samples. These are used in the Ridge regression.
For the values in the block it is straightforward, and it is already implemented. The problems are the derivatives. Also because I do not know how much can be used the true derivative of the variance:
`Grad[Var[X]] = 2(E[X Grad[X]] - E[X]E[Grad[X]])`
for the std:
`Grad[Std(X)]=0.5(Grad[Var[X]])/Std(X)= (E[X Grad[X]] - E[X]E[Grad[X]])/Std(X)`
what do you think?
=> added std and variance

equistore-core/include/equistore.h, equistore-core/include/equistore.hpp, equistore-core/src/blocks.rs, equistore-core/src/c_api/blocks.rs, equistore-core/src/c_api/tensor.rs, equistore-core/src/data.rs, equistore-core/src/tensor/mod.rs, equistore-core/tests/cpp/blocks.cpp, equistore-core/tests/cpp/tensor.cpp, equistore/src/block/block_ref.rs, equistore/src/c_api.rs, equistore/src/tensor.rs, python/src/equistore/_c_api.py, python/src/equistore/block.py, python/src/equistore/tensor.py, python/tests/tensor.py
=> Allow to copy TensorMap

python/src/equistore/operations/reduce_over_samples.py, python/tests/operations/reduce_over_samples.py
solve #158 
```python
block = TensorBlock(
values=np.zeros([0, 1]),
properties=Labels(["prop"], np.zeros([1, 1], dtype=int)),
samples=Labels(["structure"], np.empty((0, 1), dtype=np.int32)),
components=[],
)
result_block = TensorBlock(
values=np.zeros([0, 1]),
properties=Labels(["prop"], np.zeros([1, 1], dtype=int)),
samples=Labels([], np.empty((0, 0), dtype=np.int32)),
components=[],
)
tensor = TensorMap(Labels.single(), [block])
result_tensor = TensorMap(Labels.single(), [result_block])
tensor_sum = equistore.sum_over_samples(tensor, "structure")
self.assertTrue(equistore.equal(result_tensor, tensor_sum))
```
or for gradient 
```python
block = TensorBlock(
values=np.array(
[[1, 2, 4], [3, 5, 6], [-1.3, 26.7, 4.54], [3.5, 5.3, 6.87]]
),
samples=Labels(
["structure", "samples1"], …
```
=> solve the problem of zero sample

docs/src/reference/python/index.rst, docs/src/reference/python/misc.rst, docs/src/reference/python/misc/errors.rst, docs/src/reference/python/misc/index.rst, equistore-core/CMakeLists.txt, equistore/build.rs, equistore/src/lib.rs, python/src/equistore/block.py, python/src/equistore/io.py, python/src/equistore/utils.py
This is built on top of #161, which should be merged first
=> Small improvements for the rascaline integration

equistore-core/CMakeLists.txt, equistore-core/cmake/equistore-config.in.cmake, equistore/Cargo.toml, equistore/build.rs, equistore/equistore-core, equistore/src/lib.rs, equistore/tests/serialization.rs
----
:books: Documentation preview :books:: https://equistore--173.org.readthedocs.build/en/173/
=> More build system improvements for Rust/C/C++

python/src/equistore/operations/add.py, python/src/equistore/operations/multiply.py, python/src/equistore/operations/subtract.py, python/tests/operations/add.py, python/tests/operations/divide.py, python/tests/operations/multiply.py, python/tests/operations/pow.py, python/tests/operations/subtract.py
Fixes #206 #207 
----
:books: Documentation preview :books:: https://equistore--208.org.readthedocs.build/en/208/
=> Fix inplace operation bug, add tests

docs/src/reference/python/operations/math/abs.rst, docs/src/reference/python/operations/math/index.rst, python/src/equistore/operations/__init__.py, python/src/equistore/operations/_dispatch.py, python/src/equistore/operations/abs.py, python/tests/operations/abs.py
Absolute function for TensorMaps and TensorBlocks. Returns a new TensorMap with the absolute values of the given TensorMap. The returned block have the same samples, properties and components as that of the given TensorMap.
----
:books: Documentation preview :books:: https://equistore--209.org.readthedocs.build/en/209/
=> New absolute operation for TensorMaps

python/src/equistore/operations/_dispatch.py
fix _dispatch.index_add to works with GPU
----
:books: Documentation preview :books:: https://equistore--214.org.readthedocs.build/en/214/
=> fix _dispatch index_add

python/src/equistore/operations/join.py
----
:books: Documentation preview :books:: https://equistore--216.org.readthedocs.build/en/216/
=> fix bug in joining gradient.data, now uses _dispatch.vstack

equistore-core/src/tensor/mod.rs, python/tests/origin.py
Addresses #225
----
:books: Documentation preview :books:: https://equistore--228.org.readthedocs.build/en/228/
=> Ensure all blocks in a TensorMap have the same data origin

equistore-core/src/blocks.rs, python/src/equistore/operations/equal_metadata.py, python/tests/operations/equal_metadata.py
----
:books: Documentation preview :books:: https://equistore--232.org.readthedocs.build/en/232/
=> Components should always contain at least one entry

python/src/equistore/block.py
Added documentation code snippets for gradient and add_gradient
----
:books: Documentation preview :books:: https://equistore--201.org.readthedocs.build/en/201/
=> Added documentation for gradient() and add_gradient()

python/src/equistore/operations/_dispatch.py, python/src/equistore/operations/empty_like.py, python/src/equistore/operations/ones_like.py, python/src/equistore/operations/random_like.py, python/src/equistore/operations/zeros_like.py, tox.ini
----
:books: Documentation preview :books:: https://equistore--211.org.readthedocs.build/en/211/
=> added example in docstrings of empty_like, zeros_like, ones_like

python/src/equistore/block.py, python/src/equistore/labels.py, python/src/equistore/operations/allclose.py, python/src/equistore/operations/empty_like.py, python/src/equistore/operations/equal_metadata.py, python/src/equistore/operations/lstsq.py, python/src/equistore/operations/ones_like.py, python/src/equistore/operations/random_like.py, python/src/equistore/operations/reduce_over_samples.py, python/src/equistore/operations/slice.py, python/src/equistore/operations/solve.py, python/src/equistore/operations/split.py, python/src/equistore/operations/unique_metadata.py, python/src/equistore/operations/zeros_like.py, python/src/equistore/tensor.py, tox.ini
----
:books: Documentation preview :books:: https://equistore--244.org.readthedocs.build/en/244/
=> Add blackdoc to format examples/doctest code

docs/src/reference/operations/creation/block_from_array.rst, docs/src/reference/operations/creation/index.rst, python/src/equistore/operations/__init__.py, python/src/equistore/operations/block_from_array.py, python/src/equistore/operations/one_hot.py, python/tests/operations/block_from_array.py
----
:books: Documentation preview :books:: https://equistore--241.org.readthedocs.build/en/241/
=> from_array function

python/src/equistore/operations/_dispatch.py, python/src/equistore/operations/reduce_over_samples.py
fix for #247 
----
:books: Documentation preview :books:: https://equistore--250.org.readthedocs.build/en/250/
=> quick fix for type mistmatch

docs/src/reference/operations/logic/equal_metadata.rst, python/src/equistore/operations/__init__.py, python/src/equistore/operations/allclose.py, python/src/equistore/operations/equal.py, python/src/equistore/operations/equal_metadata.py, python/tests/operations/equal_metadata.py
Closes #257 
----
:books: Documentation preview :books:: https://equistore--258.org.readthedocs.build/en/258/
=> Add public `equal_metadata_block` function

equistore-core/src/blocks.rs, equistore-core/src/c_api/tensor.rs, equistore-core/src/lib.rs, equistore-core/src/tensor/keys_to_properties.rs, equistore-core/src/tensor/keys_to_samples.rs, python/equistore-core/equistore/core/io.py, python/equistore-core/equistore/core/labels.py, python/equistore-core/equistore/core/tensor.py, python/equistore-core/tests/blocks.py, python/equistore-core/tests/labels.py, python/equistore-core/tests/serialization.py, python/equistore-core/tests/tensor.py, python/equistore-operations/tests/allclose.py, python/equistore-operations/tests/equal.py
Fix #65
Fix #174 
Fix #218 
----
:books: Documentation preview :books:: https://equistore--262.org.readthedocs.build/en/262/
=> Fix all bugs

.github/workflows/python-tests.yml, .github/workflows/rust-tests.yml, CONTRIBUTING.rst, Cargo.toml, equistore-core/CMakeLists.txt, python/Cargo.toml, python/lib.rs, python/tests/run-python-tests.rs, tox.ini
----
:books: Documentation preview :books:: https://equistore--264.org.readthedocs.build/en/264/
=> Move Python test to a different CI job

.github/workflows/python-tests.yml, .github/workflows/rust-tests.yml, equistore-core/CMakeLists.txt, equistore-core/build.rs, equistore-core/cmake/equistore-config.in.cmake, equistore-core/tests/c-api-install.rs, equistore-core/tests/c-api-tests.rs, python/equistore-core/equistore/core/_c_lib.py, tox.ini
=> Check that we can build the whole project for Windows

equistore/src/block/block_ref.rs, equistore/src/data/array.rs, equistore/src/data/array_ref.rs
This is a follow up to #276 
----
:books: Documentation preview :books:: https://equistore--286.org.readthedocs.build/en/286/
=> Check for zero length in more places before creating slices

.github/workflows/rust-tests.yml, equistore-torch/include/equistore/torch/labels.hpp
----
:books: Documentation preview :books:: https://equistore--296.org.readthedocs.build/en/296/
=> Check for leftover debug printing on CI

docs/src/get-started/installation.rst, docs/src/reference/cxx/index.rst, docs/src/reference/torch/cxx/index.rst, docs/src/reference/torch/index.rst, pyproject.toml, python/equistore-torch/build-backend/backend.py
----
:books: Documentation preview :books:: https://equistore--307.org.readthedocs.build/en/307/
=> Small improvments to equistore-torch

.github/workflows/build-wheels.yml, .github/workflows/docs.yml, .github/workflows/python-tests.yml, .github/workflows/torch-tests.yml, .readthedocs.yml, python/equistore-operations/tests/abs.py
Some minor additions to the CI and the pyproject file.
----
:books: Documentation preview :books:: https://equistore--313.org.readthedocs.build/en/313/
=> Python CI adjustments

python/equistore-operations/equistore/operations/_dispatch.py
Contains:
* torch.Tensor type is always checked first so TorchScript never interprets the np.ndarray is instance check
* _check_all_same_type with its type argument is not TorchScript compatible so it was split into two functions
TODO: Need to do tests, probably I am missing more things that are not TorchScript compatible
----
:books: Documentation preview :books:: https://equistore--310.org.readthedocs.build/en/310/
=> Make dispatch TorchScript compatible

python/equistore-operations/equistore/operations/manipulate_dimension.py, python/equistore-torch/tests/operations/manipulate_dimension.py
----
:books: Documentation preview :books:: https://equistore--336.org.readthedocs.build/en/336/
=> Make `manipulate_dimensions` torch-script-able

python/equistore-operations/equistore/operations/block_from_array.py, python/equistore-torch/tests/operations/block_from_array.py
----
:books: Documentation preview :books:: https://equistore--339.org.readthedocs.build/en/339/
=> Make `block_from_array` torch-script-able

python/equistore-operations/equistore/operations/_dispatch.py, python/equistore-operations/equistore/operations/join.py, python/equistore-operations/equistore/operations/manipulate_dimension.py, python/equistore-torch/equistore/torch/operations.py, python/equistore-torch/tests/operations/join.py
Still work in progress due to the wonderful compiler.
----
:books: Documentation preview :books:: https://equistore--331.org.readthedocs.build/en/331/
=> Make join() torch-script-able

python/equistore-operations/equistore/operations/_dispatch.py, python/equistore-operations/equistore/operations/abs.py, python/equistore-torch/tests/operations/abs.py
----
:books: Documentation preview :books:: https://equistore--338.org.readthedocs.build/en/338/
=> Make `abs` torch-scriptable

python/metatensor-operations/metatensor/operations/dot.py, python/metatensor-torch/tests/operations/dot.py
----
:books: Documentation preview :books:: https://metatensor--352.org.readthedocs.build/en/352/
=> Make `dot()` torch-script-able

python/metatensor-operations/metatensor/operations/_dispatch.py, python/metatensor-operations/metatensor/operations/lstsq.py, python/metatensor-operations/metatensor/operations/solve.py, python/metatensor-torch/tests/operations/lstsq.py, python/metatensor-torch/tests/operations/solve.py
----
:books: Documentation preview :books:: https://metatensor--351.org.readthedocs.build/en/351/
=> Make linear algebra solvers torch-script-able

python/metatensor-operations/metatensor/operations/_dispatch.py, python/metatensor-operations/metatensor/operations/drop_blocks.py, python/metatensor-torch/tests/operations/drop_blocks.py
----
:books: Documentation preview :books:: https://metatensor--354.org.readthedocs.build/en/354/
=> Make `drop_blocks()` torch-script-able

docs/src/reference/python/labels.rst, python/metatensor-core/metatensor/core/data/extract.py, python/metatensor-core/metatensor/core/labels.py, python/metatensor-core/tests/labels.py
Fix #293
----
:books: Documentation preview :books:: https://metatensor--359.org.readthedocs.build/en/359/
=> Keep a reference to the Labels in Labels.values

python/metatensor-operations/metatensor/operations/_dispatch.py, python/metatensor-operations/metatensor/operations/add.py, python/metatensor-operations/metatensor/operations/divide.py, python/metatensor-operations/metatensor/operations/drop_blocks.py, python/metatensor-operations/metatensor/operations/equal_metadata.py, python/metatensor-operations/metatensor/operations/join.py, python/metatensor-operations/metatensor/operations/manipulate_dimension.py, python/metatensor-operations/metatensor/operations/multiply.py, python/metatensor-operations/metatensor/operations/pow.py, python/metatensor-operations/metatensor/operations/slice.py, python/metatensor-operations/metatensor/operations/split.py, python/metatensor-operations/metatensor/operations/subtract.py, python/metatensor-operations/metatensor/operations/to.py, python/metatensor-operations/metatensor/operations/unique_metadata.py, python/metatensor-operations/tests/add.py, python/metatensor-operations/tests/divide.py, python/metatensor-operations/tests/multiply.py, python/metatensor-operations/tests/pow.py, python/metatensor-operations/tests/slice.py, python/metatensor-operations/tests/split.py, python/metatensor-operations/tests/subtract.py, python/metatensor-operations/tests/to.py, python/metatensor-operations/tests/unique_metadata.py
----
:books: Documentation preview :books:: https://metatensor--360.org.readthedocs.build/en/360/
=> Use similar error messages for type checks in all operations

python/metatensor-operations/tests/split.py
This is the last one!
fix #176
----
:books: Documentation preview :books:: https://metatensor--363.org.readthedocs.build/en/363/
=> Port split tests to pytest

metatensor-core/src/blocks.rs, python/metatensor-core/metatensor/core/block.py, python/metatensor-core/metatensor/core/labels.py, python/metatensor-core/metatensor/core/tensor.py, python/metatensor-core/tests/blocks.py, python/metatensor-core/tests/tensor.py, python/metatensor-torch/metatensor/torch/documentation.py
Fix #104
Fix #215
----
:books: Documentation preview :books:: https://metatensor--362.org.readthedocs.build/en/362/
=> Better errors messages for wrong types/wrong values in TensorBlock

docs/src/reference/operations/set/index.rst, docs/src/reference/operations/set/sort.rst, python/metatensor-operations/metatensor/operations/__init__.py, python/metatensor-operations/metatensor/operations/_dispatch.py, python/metatensor-operations/metatensor/operations/slice.py, python/metatensor-operations/metatensor/operations/sort.py, python/metatensor-operations/tests/sort.py, python/metatensor-torch/tests/operations/sort.py
Still a draft, but some comments on the signature of the sort function are already welcomed. I marked questions for review with `PR COMMENT`
Missing:
* sorting of gradients
* dispatching np.take function
* tests
----
:books: Documentation preview :books:: https://equistore--281.org.readthedocs.build/en/281/
=> Implementation of sort operation

.github/workflows/torch-tests.yml, metatensor-torch/tests/CMakeLists.txt
Fix #377 
----
:books: Documentation preview :books:: https://metatensor--378.org.readthedocs.build/en/378/
=> Run debug+sanitizer build on CI for torch tests

metatensor-torch/src/labels.cpp, python/metatensor-torch/tests/labels.py
Built on top of #375 and #378 which should be merged first
~TODO: figure a way to test this? Since we don't have cuda on CI~
=> Preserve device in Labels::union and intersection

.github/workflows/build-wheels.yml, python/metatensor-torch/setup.py
----
:books: Documentation preview :books:: https://metatensor--393.org.readthedocs.build/en/393/
=> More fixes for the release

metatensor/Cargo.toml, scripts/package-core.sh
----
:books: Documentation preview :books:: https://metatensor--394.org.readthedocs.build/en/394/
=> Fix rust crate pre-release

docs/src/get-started/installation.rst, metatensor-core/src/c_api/status.rs, metatensor/src/block/block_mut.rs, metatensor/src/block/block_ref.rs, metatensor/src/errors.rs
A lot of people are seeing issues because they have an old pip version, this should help!
----
:books: Documentation preview :books:: https://metatensor--396.org.readthedocs.build/en/396/
=> Suggest updating pip in installation instructions

metatensor-core/src/tensor/keys_to_samples.rs, metatensor-core/src/tensor/mod.rs, metatensor-core/src/tensor/utils.rs, metatensor-torch/include/metatensor/torch/tensor.hpp, metatensor-torch/src/register.cpp, metatensor-torch/src/tensor.cpp, python/metatensor-core/metatensor/tensor.py, python/metatensor-core/tests/tensor.py, python/metatensor-operations/metatensor/operations/join.py, python/metatensor-operations/metatensor/operations/manipulate_dimension.py, python/metatensor-operations/metatensor/operations/reduce_over_samples.py, python/metatensor-operations/metatensor/operations/slice.py, python/metatensor-operations/metatensor/operations/sort.py, python/metatensor-operations/tests/join.py, python/metatensor-operations/tests/manipulate_dimension.py, python/metatensor-operations/tests/reduce_mean.py, python/metatensor-operations/tests/reduce_special_cases.py, python/metatensor-operations/tests/reduce_std.py, python/metatensor-operations/tests/reduce_sum.py, python/metatensor-operations/tests/slice.py, python/metatensor-torch/metatensor/torch/documentation.py, python/metatensor-torch/tests/operations/manipulate_dimension.py, python/metatensor-torch/tests/operations/reduce_over_samples.py, python/metatensor-torch/tests/tensor.py
----
:books: Documentation preview :books:: https://metatensor--399.org.readthedocs.build/en/399/
=> Use {sample,component,property}_names

metatensor-core/cmake/dev-versions.cmake, metatensor-core/src/c_api/labels.rs, metatensor-core/src/lib.rs, metatensor-core/src/utils.rs, metatensor-core/tests/cmake-project/CMakeLists.txt, metatensor-torch/cmake/dev-versions.cmake, metatensor-torch/src/array.cpp, metatensor-torch/tests/cmake-project/CMakeLists.txt, metatensor/src/block/block_ref.rs, python/metatensor-torch/build-backend/backend.py, scripts/build-python.sh
----
:books: Documentation preview :books:: https://metatensor--400.org.readthedocs.build/en/400/
=> Also create developement version number in CMake tests

.github/workflows/PULL_REQUEST_TEMPLATE.md, docs/requirements.txt, docs/src/conf.py, docs/src/reference/c/CHANGELOG.md, docs/src/reference/c/index.rst, docs/src/reference/cxx/CHANGELOG.md, docs/src/reference/cxx/index.rst, docs/src/reference/operations/CHANGELOG.md, docs/src/reference/operations/index.rst, docs/src/reference/python/CHANGELOG.md, docs/src/reference/python/index.rst, docs/src/reference/torch/CHANGELOG.md, docs/src/reference/torch/index.rst, metatensor-core/CHANGELOG.md, metatensor-torch/CHANGELOG.md, metatensor/CHANGELOG.md, pyproject.toml, python/metatensor-core/pyproject.toml, python/metatensor-operations/CHANGELOG.md, python/metatensor-operations/pyproject.toml, python/metatensor-torch/pyproject.toml
----
:books: Documentation preview :books:: https://metatensor--403.org.readthedocs.build/en/403/
=> Add a changelog for all packages

metatensor-torch/include/metatensor/torch/block.hpp, metatensor-torch/include/metatensor/torch/labels.hpp, metatensor-torch/include/metatensor/torch/tensor.hpp, metatensor-torch/src/block.cpp, metatensor-torch/src/labels.cpp, metatensor-torch/src/register.cpp, metatensor-torch/src/tensor.cpp, python/metatensor-torch/tests/tensor.py
Fixes #409. I've been able to write a test that fails but I don't know what the best way to fix the problem is
----
:books: Documentation preview :books:: https://metatensor--411.org.readthedocs.build/en/411/
=> Fix x_to_y labels device

metatensor-torch/include/metatensor/torch/tensor.hpp, metatensor-torch/src/block.cpp, metatensor-torch/src/misc.cpp, metatensor-torch/src/register.cpp, metatensor-torch/src/tensor.cpp, metatensor-torch/tests/block.cpp, metatensor-torch/tests/tensor.cpp, python/metatensor-torch/tests/block.py, python/metatensor-torch/tests/tensor.py
Implements #370
----
:books: Documentation preview :books:: https://metatensor--414.org.readthedocs.build/en/414/
=> Check `metatensor.torch.TensorBlock/Map` at construction

python/metatensor-torch/tests/serialization.py
Follow-up to #419 
----
:books: Documentation preview :books:: https://metatensor--422.org.readthedocs.build/en/422/
=> Create files in tempdir for tests

metatensor-core/cmake/dev-versions.cmake, python/metatensor-core/setup.py, python/metatensor-operations/setup.py, python/metatensor-operations/tests/allclose.py, python/metatensor-operations/tests/empty_like.py, python/metatensor-operations/tests/equal.py, python/metatensor-operations/tests/ones_like.py, python/metatensor-operations/tests/random_like.py, python/metatensor-operations/tests/zeros_like.py, python/metatensor-torch/setup.py, python/metatensor-torch/tests/tensor.py, scripts/n-commits-since-last-tag.py
Some people where having issues installing the code for the tutorial during the MLIP-23 workshop, this should help debug issues.
----
:books: Documentation preview :books:: https://metatensor--416.org.readthedocs.build/en/416/
=> Get more information when n-commits-since-last-tag.py fails

.gitignore, docs/src/reference/operations/manipulation/detach.rst, docs/src/reference/operations/manipulation/index.rst, docs/src/reference/operations/manipulation/remove-gradients.rst, docs/src/reference/operations/manipulation/requires-grad.rst, python/metatensor-operations/CHANGELOG.md, python/metatensor-operations/metatensor/operations/__init__.py, python/metatensor-operations/metatensor/operations/_dispatch.py, python/metatensor-operations/metatensor/operations/detach.py, python/metatensor-operations/metatensor/operations/remove_gradients.py, python/metatensor-operations/metatensor/operations/requires_grad.py, python/metatensor-operations/metatensor/operations/to.py, python/metatensor-operations/tests/detach.py, python/metatensor-operations/tests/requires_grad.py, python/metatensor-operations/tests/to.py, python/metatensor-torch/tests/operations/detach.py, python/metatensor-torch/tests/operations/requires_grad.py
This also removed `requires_grad` from the `to` operation, preparing to move the operation to metatensor-torch and metatensor-core.
Fix #149.
----
:books: Documentation preview :books:: https://metatensor--424.org.readthedocs.build/en/424/
=> Add `metatensor.detach` operation

metatensor-core/Cargo.toml, metatensor-core/build.rs, metatensor-torch/Cargo.toml, metatensor/Cargo.toml, python/Cargo.toml
This should fix CI for #431
----
📚 Documentation preview 📚: https://metatensor--437.org.readthedocs.build/en/437/
=> Update Rust dependencies

python/metatensor-torch/metatensor/torch/documentation.py
Fix #448, follow up to #309
----
📚 Documentation preview 📚: https://metatensor--449.org.readthedocs.build/en/449/
=> Update documentation for torch's TensorBlock::gradients

.github/workflows/rust-tests.yml, docs/src/core/reference/c/block.rst, docs/src/core/reference/c/misc.rst, docs/src/core/reference/cxx/misc.rst, docs/src/core/reference/python/misc.rst, python/metatensor-core/metatensor/block.py, scripts/check-c-api-docs.py, tox.ini
And a script to check that all functions are documented.
----
📚 Documentation preview 📚: https://metatensor--450.org.readthedocs.build/en/450/
=> Add missing functions to C API documentation

docs/src/core/reference/cxx/misc.rst, docs/src/torch/reference/serialization.rst, metatensor-core/CHANGELOG.md, metatensor-core/include/metatensor.hpp, metatensor-core/tests/cpp/tensor.cpp, metatensor-torch/CHANGELOG.md, metatensor-torch/include/metatensor/torch/misc.hpp, metatensor-torch/include/metatensor/torch/tensor.hpp, metatensor-torch/src/misc.cpp, metatensor-torch/src/register.cpp, metatensor-torch/src/tensor.cpp, metatensor/CHANGELOG.md, metatensor/src/io.rs, metatensor/src/tensor.rs, metatensor/tests/serialization.rs, python/metatensor-core/metatensor/tensor.py, python/metatensor-core/tests/serialization.py, python/metatensor-torch/metatensor/torch/__init__.py, python/metatensor-torch/metatensor/torch/documentation.py, python/metatensor-torch/tests/serialization.py, python/metatensor-torch/tests/tensor.py
Export load/save as free-standing functions and class members
----
📚 Documentation preview 📚: https://metatensor--453.org.readthedocs.build/en/453/
=> Export load/save as free-standing functions and class members

.github/workflows/build-wheels.yml, python/metatensor-learn/setup.py, python/metatensor-operations/setup.py, python/metatensor-torch/setup.py, setup.py
----
📚 Documentation preview 📚: https://metatensor--456.org.readthedocs.build/en/456/
=> Prepare for metatensor-learn release

python/metatensor-core/metatensor/block.py, python/metatensor-core/tests/blocks.py
=> Fix `TensorBlock.to` for multiple arguments

python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
Fix typo
----
📚 Documentation preview 📚: https://metatensor--471.org.readthedocs.build/en/471/
=> Fix typo in ase_calculator.py

python/metatensor-torch/metatensor/torch/atomistic/units.py, python/metatensor-torch/tests/atomistic/ase_calculator.py, python/metatensor-torch/tests/atomistic/model.py, python/metatensor-torch/tests/atomistic/units.py
Solves #466 
- [?] Documentation updated (for new features)?
----
📚 Documentation preview 📚: https://metatensor--474.org.readthedocs.build/en/474/
=> Fix unit issues in `metatensor.torch.atomistic`

python/metatensor-operations/CHANGELOG.md, python/metatensor-operations/metatensor/operations/join.py, python/metatensor-operations/tests/join.py
Fixes #467
Thanks for the detailed examples @jwa7.
Maybe we should update the Changelog @Luthaf. This is a breaking change.
----
📚 Documentation preview 📚: https://metatensor--476.org.readthedocs.build/en/476/
=> Add `sort_samples` argument to `join`

CONTRIBUTING.rst, docs/extensions/versions_list.py, docs/src/atomistic/reference/index.rst, docs/src/conf.py, docs/src/core/reference/c/index.rst, docs/src/core/reference/cxx/index.rst, docs/src/core/reference/python/index.rst, docs/src/devdoc/versions.rst, docs/src/installation.rst, docs/src/learn/index.rst, docs/src/learn/reference/index.rst, docs/src/operations/reference/index.rst, docs/src/torch/reference/index.rst
----
📚 Documentation preview 📚: https://metatensor--477.org.readthedocs.build/en/477/
=> Small documentation updates following the releases

python/metatensor-core/metatensor/block.py
----
:books: Documentation preview :books:: https://equistore--204.org.readthedocs.build/en/204/
=> Added doctest for TensorBlock usage and add_gradient.

python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py, python/metatensor-torch/tests/atomistic/ase_calculator.py
Part of #430.
We added an ASE calculator for metatensor models in #405, leaving `fromdict` and `todict` unimplemented, this PR tries to add these functions (which are standard and required in ASE as far as I understand).
----
📚 Documentation preview 📚: https://metatensor--472.org.readthedocs.build/en/472/
=> Implement todict and fromdict for ASE calculator

python/metatensor-learn/metatensor/learn/nn/module_map.py
Make the linter happy again!
----
📚 Documentation preview 📚: https://metatensor--490.org.readthedocs.build/en/490/
=> Fix line length module_map.py

docs/src/learn/reference/index.rst, docs/src/operations/reference/index.rst, python/metatensor-learn/CHANGELOG.md
Maybe this is something we should do as part of the "make a release PR" to minimize commit noise a bit.
----
📚 Documentation preview 📚: https://metatensor--498.org.readthedocs.build/en/498/
=> Add new releases to the documentation

metatensor/CHANGELOG.md, metatensor/Cargo.toml
Same as #508 but for the rust crate
----
📚 Documentation preview 📚: https://metatensor--509.org.readthedocs.build/en/509/
=> Release metatensor-rust v0.1.3

docs/src/installation.rst
When reading the `installation.rst` it is not really clear to me, what we are building when `METATENSOR_INSTALL_BOTH_STATIC_SHARED` is turned off.  I added a small sentence to clarify this.
----
📚 Documentation preview 📚: https://metatensor--507.org.readthedocs.build/en/507/
=> Better docs for `METATENSOR_INSTALL_BOTH_STATIC_SHARED`

metatensor-torch/src/labels.cpp, python/metatensor-core/metatensor/labels.py, python/metatensor-operations/metatensor/operations/_backend.py, python/metatensor-operations/metatensor/operations/manipulate_dimension.py, python/metatensor-operations/tests/manipulate_dimension.py, python/metatensor-torch/metatensor/torch/operations.py, python/metatensor-torch/tests/operations/manipulate_dimension.py
Fix #518
First half of the PR, dealing with the Labels. @jwa7 will take over to handle the operations side of things.
----
📚 Documentation preview 📚: https://metatensor--519.org.readthedocs.build/en/519/
=> Add checks for the new values size in Labels::insert

.github/workflows/coverage.yml, CONTRIBUTING.rst, pyproject.toml, tox.ini
While checking what we do here to help setup coverage on metatensor-models, I found a couple of issues.
----
📚 Documentation preview 📚: https://metatensor--531.org.readthedocs.build/en/531/
=> Small coverage improvements

.github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/python-tests.yml
This should fix CI for #542 (and friends)
----
📚 Documentation preview 📚: https://metatensor--543.org.readthedocs.build/en/543/
=> Pin tox to 4.14.0

python/metatensor-torch/metatensor/torch/documentation.py
Fix #561 
----
📚 Documentation preview 📚: https://metatensor--562.org.readthedocs.build/en/562/
=> Add missing Labels.device documentation

.github/workflows/build-wheels.yml, python/scripts/rustc-manylinux2014_aarch64/Dockerfile
Fix #461 
----
📚 Documentation preview 📚: https://metatensor--563.org.readthedocs.build/en/563/
=> Linux aarch64 wheels

.github/workflows/build-wheels.yml, .github/workflows/comment-wheels-pr.yml
This is a new, non-backward compatible version using a different backend on github side.
----
📚 Documentation preview 📚: https://metatensor--572.org.readthedocs.build/en/572/
=> Update to CI upload-artifact@v4

.github/workflows/build-wheels.yml, python/metatensor-torch/build-backend/backend.py, scripts/build-all-wheels.sh
This tries to build metatensor_torch wheels we can publish on PyPI, following #564.
----
📚 Documentation preview 📚: https://metatensor--571.org.readthedocs.build/en/571/
=> Build metatensor-torch for all supported torch versions

docs/src/atomistic/overview.rst, docs/src/atomistic/reference/cxx/systems.rst, docs/src/atomistic/reference/systems.rst, metatensor-torch/CHANGELOG.md, metatensor-torch/include/metatensor/torch/atomistic/system.hpp, metatensor-torch/src/atomistic/system.cpp, metatensor-torch/src/register.cpp, metatensor-torch/tests/atomistic.cpp, python/metatensor-torch/metatensor/torch/atomistic/__init__.py, python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py, python/metatensor-torch/metatensor/torch/atomistic/documentation.py, python/metatensor-torch/metatensor/torch/atomistic/model.py, python/metatensor-torch/tests/atomistic/model.py, python/metatensor-torch/tests/atomistic/neighbors.py, python/metatensor-torch/tests/atomistic/systems.py, tox.ini
Someday I'll manage to put `s` at the right places. 
This is a breaking change, do we want to merge & release 0.5.0? Otherwise we can keep this as a PR for a while longer and merge it later.
This was split out of #550.
----
📚 Documentation preview 📚: https://metatensor--587.org.readthedocs.build/en/587/
=> Rename neighbors list to neighbor list

docs/src/atomistic/index.rst, docs/src/atomistic/overview.rst, docs/src/core/index.rst, docs/src/core/overview.rst, docs/src/core/reference/c/index.rst, docs/src/core/reference/cxx/index.rst, docs/src/core/reference/python/data.rst, docs/src/core/reference/python/index.rst, docs/src/core/reference/rust/index.rst, docs/src/goals.rst, docs/src/index.rst, docs/src/installation.rst, docs/src/learn/index.rst, docs/src/learn/reference/index.rst, docs/src/operations/index.rst, docs/src/operations/reference/index.rst, docs/src/operations/torch.rst, docs/src/torch/index.rst, docs/src/torch/reference/cxx/index.rst, docs/src/torch/reference/index.rst, python/metatensor-core/metatensor/data/extract.py, python/metatensor-torch/metatensor/torch/atomistic/model.py
This incorporates most of the feedback from @sirmarcel on the documentation, except for a couple of points we'll need to discuss in person. Many thanks for this feedback, it was very detailed and useful!
----
📚 Documentation preview 📚: https://metatensor--550.org.readthedocs.build/en/550/
=> Mulitple documentation improvements

docs/src/learn/reference/nn/index.rst, python/metatensor-learn/CHANGELOG.md, python/metatensor-learn/metatensor/learn/nn/__init__.py, python/metatensor-learn/metatensor/learn/nn/relu.py, python/metatensor-learn/metatensor/learn/nn/silu.py, python/metatensor-learn/metatensor/learn/nn/tanh.py, python/metatensor-learn/tests/relu.py, python/metatensor-learn/tests/sequential.py, python/metatensor-learn/tests/silu.py, python/metatensor-torch/tests/learn/torchscript.py
----
📚 Documentation preview 📚: https://metatensor--597.org.readthedocs.build/en/597/
=> Implement `ReLU` and `SiLU` module maps in `mts.learn.nn`

docs/src/installation.rst
Fix #593
----
📚 Documentation preview 📚: https://metatensor--598.org.readthedocs.build/en/598/
=> Document workaround for torch's cmake issues

.github/dependabot.yml
Hopefully, last PR touching the bot.
----
📚 Documentation preview 📚: https://metatensor--604.org.readthedocs.build/en/604/
=> Check actions only every month

docs/src/core/reference/c/index.rst, docs/src/core/reference/cxx/index.rst, docs/src/core/reference/python/index.rst, metatensor-core/CHANGELOG.md, metatensor-core/Cargo.toml, rust/metatensor-sys/Cargo.toml
This is a bugfix release (like the last 3 :smiley:), fixing compilation in some corner cases
----
📚 Documentation preview 📚: https://metatensor--608.org.readthedocs.build/en/608/
=> Release metatensor-core v0.1.6

docs/src/core/reference/c/misc.rst, docs/src/core/reference/cxx/misc.rst, docs/src/torch/reference/cxx/miscellaneous.rst, metatensor-core/CHANGELOG.md, metatensor-core/CMakeLists.txt, metatensor-core/cmake/version-defines.cmake, metatensor-core/include/metatensor.h, metatensor-core/src/c_api/mod.rs, metatensor-core/tests/cpp/misc.cpp, metatensor-torch/CHANGELOG.md, metatensor-torch/CMakeLists.txt, metatensor-torch/include/metatensor/torch.hpp, metatensor-torch/include/metatensor/torch/misc.hpp, metatensor-torch/src/misc.cpp, metatensor-torch/tests/misc.cpp
These will allow downstream code to do conditional compilation depending on the version they are using
----
📚 Documentation preview 📚: https://metatensor--613.org.readthedocs.build/en/613/
=> Add METATENSOR_VERSION macro and friends

docs/src/core/reference/c/index.rst, docs/src/core/reference/cxx/index.rst, docs/src/core/reference/python/index.rst, metatensor-core/CHANGELOG.md, metatensor-core/Cargo.toml, rust/metatensor-sys/Cargo.toml, rust/metatensor/src/data/array_ref.rs
----
📚 Documentation preview 📚: https://metatensor--615.org.readthedocs.build/en/615/
=> Release metatensor-core v0.1.7

.github/workflows/comment-download.yml
` is used for string formatting in JS.
This should fix the error in https://github.com/lab-cosmo/metatensor/actions/runs/9060508099
=> Fix syntax in wheels comment workflow

docs/src/learn/reference/index.rst, python/metatensor-learn/CHANGELOG.md, python/metatensor-learn/setup.py
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1509387090.zip)
=> Release metatensor-learn v0.2.2

metatensor-torch/src/atomistic/system.cpp
We where creating a new variable instead of updating the global one.
=> Actually use a higher epsilon for float32 when checking NL

metatensor-torch/src/atomistic/system.cpp, python/metatensor-torch/tests/atomistic/examples.py
This adds a small additional check when wrapping neighbors list.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1544085069.zip)
=> Check that neighbors list samples are in bounds

docs/src/atomistic/index.rst, docs/src/goals.rst, python/metatensor-operations/tests/data/README.md
Another aftermath to the renaming of `metatensor-models` to `metatensor`.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1589686768.zip)
=> Update links to metatrain

python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
Removes a stray line in the ASE calculator
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1608038347.zip)
=> Remove unintended (?) line in ASE calculator

docs/src/operations/reference/index.rst, python/metatensor-operations/CHANGELOG.md, python/metatensor-operations/setup.py
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1617613526.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1617685852.zip)
=> Release metatensor-operations 0.2.2

.github/workflows/coverage.yml, python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
The model returns a dict of TensorMap, not a dict of TensorBlock
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1624570731.zip)
=> Fix type annotation in ASE calculator

python/metatensor-operations/tests/_gradcheck.py, python/metatensor-operations/tests/add.py
Follow up to #479.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1663753240.zip)
=> Use a fixed seed for finite differences tests

python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
As in the title
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1670521739.zip)
=> Correct wrong return type hint in ASE calculator

python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
I think the ASE calculator is more readable this way. Especially for people who are not familiar with torch and who want to understand what our stress convention is. Open to discussion
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1673218812.zip)
=> Improve readability of ASE calculator code

python/metatensor-torch/setup.py
We already have a fixed version of `FindCUDNN.cmake` that does not need to get the version number from headers. The current hack would fail on read-only file systems.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1686090039.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1686161038.zip)
=> Remove CuDNN cmake hack in setup.py

docs/src/atomistic/overview.rst, docs/src/atomistic/reference/systems.rst, python/metatensor-core/setup.py, python/metatensor-torch/metatensor/torch/atomistic/documentation.py
Fix #686 
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1695615948.zip)
=> Add register_autograd_neighbors to the documentation

docs/src/core/reference/c/index.rst, docs/src/core/reference/cxx/index.rst, docs/src/core/reference/python/index.rst, metatensor-core/CHANGELOG.md, metatensor-core/Cargo.toml, metatensor-core/tests/cmake-project/CMakeLists.txt, rust/metatensor-sys/Cargo.toml
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1701467674.zip)
=> Release metatensor-core v0.1.9

python/metatensor-torch/metatensor/torch/atomistic/model.py, python/metatensor-torch/tests/atomistic/model.py
As in the title. Do we want to update the types for the documentation?
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1729559919.zip)
=> Support path objects for saving and loading atomistic models

.github/workflows/python-tests.yml, .github/workflows/torch-tests.yml, metatensor-torch/src/labels.cpp, metatensor-torch/tests/utils/mod.rs, python/metatensor-torch/tests/operations/reduce_over_samples.py, tox.ini
Fix the build with the new torch release and build metatensor-torch wheels for this version.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1811697448.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1756405490.zip)
=> Fixes for Torch 2.4

.github/workflows/rust-tests.yml, python/examples/atomistic/3-atomistic-model-with-nl.py, python/metatensor-torch/metatensor/torch/atomistic/model.py
We will want to check this even if we don't check the rest of the inputs, since this is a very common issue.
Fix #713 
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1853399510.zip)
=> Always check that the model supports the input atomic types

docs/src/core/reference/c/index.rst, docs/src/core/reference/cxx/index.rst, docs/src/core/reference/python/index.rst, metatensor-core/CHANGELOG.md, metatensor-core/Cargo.toml, metatensor-core/tests/cmake-project/CMakeLists.txt, metatensor-torch/CMakeLists.txt, python/metatensor-operations/setup.py, rust/metatensor-sys/Cargo.toml
This releases Labels::select and the TensorBlock serialization.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1864608206.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1864695463.zip)
=> Release metatensor-core v0.1.10

docs/src/learn/reference/index.rst, docs/src/operations/reference/index.rst, python/metatensor-learn/CHANGELOG.md, python/metatensor-learn/setup.py, python/metatensor-operations/CHANGELOG.md, python/metatensor-operations/setup.py
These have small improvements from a while ago that people might want to use.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/lab-cosmo/metatensor/actions/artifacts/1865318495.zip)
=> Release metatensor-learn and metatensor-operations v0.2.3

.github/workflows/docs.yml, CONTRIBUTING.rst, README.md, docs/src/atomistic/overview.rst, docs/src/devdoc/index.rst, docs/src/devdoc/versions.rst, docs/src/installation.rst, docs/src/operations/index.rst, julia/README.md, metatensor-core/CHANGELOG.md, metatensor-core/src/io/tensor.rs, metatensor-torch/CHANGELOG.md, metatensor-torch/tests/labels.cpp, pyproject.toml, python/metatensor-core/pyproject.toml, python/metatensor-core/tests/labels.py, python/metatensor-learn/CHANGELOG.md, python/metatensor-learn/pyproject.toml, python/metatensor-operations/CHANGELOG.md, python/metatensor-operations/pyproject.toml, python/metatensor-torch/pyproject.toml, rust/metatensor-sys/Cargo.toml, rust/metatensor/CHANGELOG.md, rust/metatensor/Cargo.toml
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/1891660011.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/1891826583.zip)
=> Update repository URL after transfer

rust/metatensor/CHANGELOG.md, rust/metatensor/Cargo.toml
This is a new breaking change, since changing the version of publicly exposed dependencies will break downstream users.
=> Release metatensor-rust v0.2.0

python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
This should reduce the number of cuda synchronization when running on device
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2028874813.zip)
=> ASE calculator: run backward before moving data back to CPU

python/metatensor-operations/CHANGELOG.md, python/metatensor-operations/setup.py
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2045848047.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2046017412.zip)
=> Release metatensor-operations v0.2.4

metatensor-core/src/labels.rs
The previous default of 4 was a problem when storing neighbors samples in atomistic model, which have 5 dimensions. 
In the torch-pme LAMMPS benchmark, this brings the cost of creating neighbor samples Labels for 167944 pairs from 14ms down to 7.5ms.
Out of the remaining 7.5ms, 2.5ms is copying the entries in the internal array and 5ms is constructing the HashMap. I'll think about ways to mitigate this (e.g. the HashMap could be lazily initialized easily, this would be harder for the internal array, …).
=> Use larger SmallVec to store Labels entries in HashMap

pyproject.toml, python/metatensor-core/metatensor/__init__.py, python/metatensor-core/metatensor/io/__init__.py, python/metatensor-core/metatensor/tensor.py, python/metatensor-core/metatensor/utils.py, python/metatensor-learn/metatensor/learn/__init__.py, python/metatensor-learn/metatensor/learn/nn/__init__.py, python/metatensor-learn/metatensor/learn/nn/layer_norm.py, python/metatensor-learn/metatensor/learn/nn/sequential.py, python/metatensor-learn/tests/layer_norm.py, python/metatensor-operations/metatensor/operations/__init__.py, python/metatensor-operations/metatensor/operations/divide.py, python/metatensor-operations/metatensor/operations/multiply.py, python/metatensor-torch/metatensor/torch/__init__.py, python/metatensor-torch/metatensor/torch/_c_lib.py, python/metatensor-torch/metatensor/torch/atomistic/__init__.py, python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py, python/metatensor-torch/metatensor/torch/atomistic/model.py, python/metatensor-torch/metatensor/torch/atomistic/systems_to_torch.py, python/metatensor-torch/metatensor/torch/learn.py, python/metatensor-torch/metatensor/torch/operations.py, python/metatensor-torch/tests/atomistic/metadata.py, python/metatensor-torch/tests/atomistic/systems_to_torch.py, tox.ini
Got sufficiently pestered by flake8 to do this. I think none of the checklist items apply.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2082859285.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2083079029.zip)
=> Switch to ruff for linting

.github/workflows/build-wheels.yml, .github/workflows/python-tests.yml, .github/workflows/torch-tests.yml, metatensor-torch/tests/utils/mod.rs, python/metatensor-core/metatensor/labels.py, python/metatensor-core/metatensor/tensor.py, python/metatensor-core/pyproject.toml, python/metatensor-operations/metatensor/operations/sort.py, python/metatensor-torch/setup.py, python/metatensor-torch/tests/atomistic/neighbors.py, tox.ini
This one seems to just work!
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2088125357.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2088327629.zip)
=> Update to Torch 2.5

python/metatensor-torch/metatensor/torch/atomistic/model.py, python/metatensor-torch/tests/atomistic/examples.py
I wrap to export and wrapped to exported
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2099052224.zip)
=> changed wrap to export in listed files

CONTRIBUTING.rst
changed one word in the documentation to the correct test name
- [] Tests updated (for new features and bugfixes)?
- [ x] Documentation updated (for new features)?
- [ x] Issue referenced (for PRs that solve an issue)?
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2099736394.zip)
=> changed documentation operations-notorch-tests to operations-numpy-tests

python/metatensor-torch/metatensor/torch/atomistic/ase_calculator.py
Speeds up the ASE calculator by speeding up the NL filtering.
With the new changes, the filtering is negligible compared to the time it takes to build the NL (with vesin).
~~- [ ] Tests updated (for new features and bugfixes)?~~
~~- [ ] Documentation updated (for new features)?~~
~~- [ ] Issue referenced (for PRs that solve an issue)?~~
~~- [ ] CHANGELOG updated with public API or any other important changes?~~
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2111701974.zip)
=> Faster ASE NL filtering

docs/src/operations/reference/index.rst, python/metatensor-operations/CHANGELOG.md, python/metatensor-operations/setup.py
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2119081864.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2119249736.zip)
=> Release metatensor-operations v0.3.0

docs/src/learn/reference/index.rst, python/metatensor-learn/CHANGELOG.md, python/metatensor-learn/setup.py
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2122898482.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2123062034.zip)
=> Release metatensor-learn v0.3.0

python/metatensor-learn/metatensor/learn/nn/layer_norm.py, python/metatensor-learn/metatensor/learn/nn/linear.py, python/metatensor-learn/metatensor/learn/nn/relu.py, python/metatensor-learn/metatensor/learn/nn/silu.py, python/metatensor-learn/metatensor/learn/nn/tanh.py, python/metatensor-learn/tests/linear.py
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2152401693.zip)
=> Fix bug in default value for `invariant_keys` in `learn.nn` modules

python/metatensor-torch/metatensor/torch/atomistic/model.py, python/metatensor-torch/tests/atomistic/model.py
Slightly adjusted the `init` logic (again) to finally allow recreating models.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2157535806.zip)
=> Allow re-creation of atomistic models

.github/workflows/build-wheels.yml, .github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/julia-tests.yml, .github/workflows/python-tests.yml, .github/workflows/rust-tests.yml, .github/workflows/torch-tests.yml, CONTRIBUTING.rst, README.md, docs/src/conf.py, docs/src/devdoc/index.rst, metatensor-core/src/io/tensor.rs
This should contain all code changes necessary to rename `master` to `main`
#748
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2108593037.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2108625353.zip)
=> Rename `master` to `main` in code

docs/src/conf.py, docs/src/core/overview.rst, docs/src/goals.rst, python/examples/core/1-first-steps.py, python/examples/core/2-handling-sparsity.py, python/examples/core/radial-spectrum.py.example, python/examples/core/spherical-expansion.py.example, python/metatensor-core/metatensor/__init__.py, python/metatensor-learn/tests/_rotation_utils.py, python/metatensor-learn/tests/_tests_utils.py, python/metatensor-operations/tests/data/README.md, python/metatensor-torch/metatensor/torch/atomistic/_extensions.py, python/metatensor-torch/metatensor/torch/atomistic/documentation.py
This update the special handling for the corresponding TorchScript extension, and all references in the code/docs.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2202079835.zip)
=> rascaline was renamed to featomic

python/metatensor-torch/metatensor/torch/atomistic/documentation.py
Updates the Python docs of `System` to include PBCs
- ~Tests updated (for new features and bugfixes)?~
- ~Issue referenced (for PRs that solve an issue)?~
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2253328189.zip)
=> Update Python docs of `System` to include PBCs

python/metatensor-torch/metatensor/torch/atomistic/model.py
As in the title
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2285754152.zip)
=> Set `requires_grad=False` for model parameters before exporting

docs/src/core/reference/python/labels.rst, docs/src/core/reference/python/tensor.rst
Fix #803 
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2299791850.zip)
=> Add special methods to the documentation of core classes

metatensor-core/Cargo.toml, metatensor-torch/CHANGELOG.md, metatensor-torch/Cargo.toml, metatensor-torch/include/metatensor/torch/atomistic/system.hpp, metatensor-torch/src/atomistic/system.cpp, metatensor-torch/src/register.cpp, python/Cargo.toml, python/metatensor_torch/metatensor/torch/atomistic/documentation.py, python/metatensor_torch/tests/atomistic/systems.py, rust/metatensor-sys/Cargo.toml
This allows for more kinds of data to be stored.
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2337629985.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2338139200.zip)
=> Change custom System data from TensorBlock to TensorMap

docs/src/atomistic/reference/index.rst, docs/src/atomistic/reference/serialization.rst, metatensor-torch/CHANGELOG.md, metatensor-torch/src/atomistic/system.cpp, pyproject.toml, python/metatensor_torch/metatensor/torch/_c_lib.py, python/metatensor_torch/metatensor/torch/atomistic/__init__.py, python/metatensor_torch/metatensor/torch/atomistic/ase_calculator.py, python/metatensor_torch/metatensor/torch/atomistic/io.py, python/metatensor_torch/metatensor/torch/atomistic/systems_to_torch.py, python/metatensor_torch/metatensor/torch/learn.py, python/metatensor_torch/metatensor/torch/operations.py, python/metatensor_torch/tests/atomistic/io.py
Replaces #673, uses a new `mta` format
----
Edit by @Luthaf:
The idea here is to define the file format for System serialization, but only implement it in Python for now. A lower level implementation will be added later.
---
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2343299320.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2343466943.zip)
=> Implement serialization for `System`

.github/workflows/build-wheels.yml, .github/workflows/julia-tests.yml, .github/workflows/python-tests.yml, .github/workflows/rust-tests.yml, .github/workflows/torch-tests.yml
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2390968984.zip)
⚙️ [Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/2391142609.zip)
=> Fix the build with mingw

metatensor-torch/src/block.cpp, metatensor-torch/src/tensor.cpp, python/metatensor_torch/tests/serialization.py
Closes #810
----
📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2395244172.zip)
=> Better `float32` error in `save()`

metatensor-core/src/blocks.rs, metatensor-core/src/c_api/blocks.rs, metatensor-core/src/labels.rs, metatensor-core/src/lib.rs, python/metatensor_core/metatensor/io/_labels.py, python/metatensor_learn/metatensor/learn/data/_namedtuple.py, python/metatensor_learn/tests/module_map.py, python/metatensor_operations/tests/split.py, python/metatensor_torch/metatensor/torch/atomistic/ase_calculator.py, python/metatensor_torch/tests/learn/module_map.py, python/scripts/generate-declarations.py, rust/metatensor/src/block/block_mut.rs, rust/metatensor/src/block/block_ref.rs, rust/metatensor/src/labels.rs, rust/metatensor/src/tensor.rs
@jwa7 since that error message tripped you up, is this better?
=> Better error message for mismatched shape/labels

metatensor-core/include/metatensor.hpp, metatensor-torch/src/atomistic/system.cpp, metatensor-torch/src/block.cpp, metatensor-torch/src/labels.cpp, metatensor-torch/src/register.cpp, metatensor-torch/src/tensor.cpp, metatensor-torch/tests/misc.cpp, metatensor-torch/tests/shared-libraries.cpp
=> Run clang-tidy on C++ code

python/metatensor_learn/tests/linear.py, python/metatensor_torch/setup.py, scripts/git-version-info.py, tox.ini
See the commit messages for descriptions.
=> Multiple small fixes

metatensor-torch/src/atomistic/model.cpp
This warning can spam the user. E.g.
```
[W112 16:05:29.651712095 model.cpp:1083] Warning: unknown quantity 'force', only [energy length] are supported (function valid_quantity)
[W112 16:05:29.651728443 model.cpp:1083] Warning: unknown quantity 'force', only [energy length] are supported (function valid_quantity)
[W112 16:05:29.692182395 model.cpp:1083] Warning: unknown quantity 'force', only [energy length] are supported (function valid_quantity)
[W112 16:05:29.692200416 model.cpp:1083] Warning: unknown quantity 'force', only [energy length] are supported (function valid_quantity)
[W112 16:05:29.744088207 model.cpp:1083] Warning: unknown quantity 'force', only [energy length] are supported (function valid_quantity)
[W112 16:05:29.744104485 model.cpp:1083] Warning: unknown quantity …
```
=> Warn only once for unknown quantities

docs/src/learn/reference/index.rst, python/metatensor_learn/CHANGELOG.md, python/metatensor_learn/setup.py
=> Release metatensor-learn v0.3.1

metatensor-torch/src/labels.cpp, metatensor-torch/tests/labels.cpp, python/metatensor_core/metatensor/labels.py, python/metatensor_torch/tests/labels.py
Fixes #832 
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2528575853.zip)
=> Try to avoid checks for empty Labels

python/metatensor_operations/metatensor/operations/sort.py, python/metatensor_operations/tests/sort.py
Fixes #839 .
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2528457390.zip)
=> Fix sorting for empty blocks

python/metatensor_operations/metatensor/operations/reduce_over_samples.py, python/metatensor_operations/tests/reduce_mean_block.py, python/metatensor_operations/tests/reduce_std_block.py, python/metatensor_operations/tests/reduce_sum_block.py
improves #854 
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2591010823.zip)
=> is it a bug or a feature?

.github/workflows/build-wheels.yml, .github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/python-tests.yml, .github/workflows/torch-tests.yml, CONTRIBUTING.rst, metatensor-torch/tests/utils/mod.rs, python/scripts/rustc-manylinux_2_28_aarch64/Dockerfile, tox.ini
=> Update to torch 2.6 and Python 3.13

python/metatensor_torch/metatensor/torch/atomistic/_extensions.py
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2603553476.zip)
=> Include gomp as a `featomic` dependency

metatensor-core/src/tensor/mod.rs
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2599663057.zip)
=> Improve error

python/metatensor_torch/metatensor/torch/atomistic/_extensions.py
Similar to #863, but for `sphericart`
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2754369343.zip)
=> Fix extensions for sphericart torch

python/metatensor_torch/metatensor/torch/atomistic/_extensions.py
Follow-up to #874, now with a single function for all `libgomp` handling; and not adding `sphericart.so` to the dependencies, since it is not needed.
=> Cleaner handling of libgomp in extensions

metatensor-torch/CHANGELOG.md, python/metatensor_torch/metatensor/torch/atomistic/ase_calculator.py, python/metatensor_torch/tests/atomistic/ase_calculator.py
Fixes #715
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2838487885.zip)
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2839350424.zip)
=> Add batching to `run_model`

metatensor-torch/CHANGELOG.md, python/metatensor_torch/metatensor/torch/atomistic/ase_calculator.py, python/metatensor_torch/tests/atomistic/ase_calculator.py
Adds `compute_energy` as an easy batched evaluator of energies, forces and stresses
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2839690907.zip)
=> Add `compute_energy` as an easy batched evaluator of energies, forces and stresses

docs/src/core/reference/c/labels.rst, julia/src/generated/_c_api.jl, metatensor-core/CHANGELOG.md, metatensor-core/include/metatensor.h, metatensor-core/include/metatensor.hpp, metatensor-core/src/c_api/labels.rs, metatensor-core/src/labels.rs, metatensor-core/tests/cpp/labels.cpp, metatensor-torch/CHANGELOG.md, metatensor-torch/include/metatensor/torch/labels.hpp, metatensor-torch/src/labels.cpp, metatensor-torch/src/register.cpp, python/metatensor_core/metatensor/_c_api.py, python/metatensor_core/metatensor/labels.py, python/metatensor_core/tests/labels.py, python/metatensor_torch/metatensor/torch/documentation.py, python/metatensor_torch/tests/labels.py, rust/metatensor-sys/src/c_api.rs, rust/metatensor/CHANGELOG.md, rust/metatensor/src/labels.rs
Implement `Labels::difference`
FIxes #710.
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2549072365.zip)
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2917566124.zip)
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2902926239.zip)
=> Add `Labels::difference` to metatensor-core and all bindings

docs/src/core/reference/c/index.rst, docs/src/core/reference/cxx/index.rst, docs/src/core/reference/python/index.rst, metatensor-core/CHANGELOG.md, metatensor-core/Cargo.toml, metatensor-core/tests/cmake-project/CMakeLists.txt, metatensor-torch/CMakeLists.txt, python/metatensor_core/CMakeLists.txt, python/metatensor_operations/setup.py, python/metatensor_torch/build-backend/backend.py, python/metatensor_torch/setup.py, rust/metatensor-sys/Cargo.toml, rust/metatensor/CHANGELOG.md, rust/metatensor/Cargo.toml
=> Release metatensor-core v0.1.13

docs/src/core/overview.rst, docs/src/goals.rst, docs/src/operations/torch.rst
Small fixes for the documentation, which I spotted while going through (parts of) it.
=> Small fixes to the documentation

.github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/julia-tests.yml, .github/workflows/python-tests.yml, .github/workflows/rust-tests.yml, .github/workflows/torch-tests.yml, metatensor-core/src/c_api/blocks.rs, metatensor-core/src/c_api/data.rs, metatensor-core/src/c_api/io/block.rs, metatensor-core/src/c_api/io/labels.rs, metatensor-core/src/c_api/io/mod.rs, metatensor-core/src/c_api/io/tensor.rs, metatensor-core/src/c_api/labels.rs, metatensor-core/src/c_api/mod.rs, metatensor-core/src/c_api/status.rs, metatensor-core/src/c_api/tensor.rs, metatensor-core/src/data.rs, metatensor-core/src/labels.rs, metatensor-torch/tests/utils/mod.rs, rust/metatensor/src/data/array.rs, rust/metatensor/src/io/mod.rs
=> Stop using ubuntu-20.04 on CI, it is deprecated

metatensor-core/CMakeLists.txt
Otherwise the wheels are a lot larger than needed
=> Make sure to strip libmetatensor.so in `metatensor-core` wheels

python/metatensor_operations/metatensor/operations/_reduce_over_samples.py, python/metatensor_operations/tests/reduce_std_block.py
=> Use an implementation less sensitive to numerical noise for std/var over samples

python/metatensor_learn/metatensor/learn/_backend.py, python/metatensor_operations/metatensor/operations/_backend.py
Changes to this function without a breaking version number increase is why we are having some difficulties updating right now, so let's make sure not to repeat this.
=> Add a note that functions in `_backend` are part of the public API

metatensor-core/CHANGELOG.md, metatensor-torch/CHANGELOG.md, metatensor-torch/include/metatensor/torch/block.hpp, metatensor-torch/include/metatensor/torch/labels.hpp, metatensor-torch/include/metatensor/torch/tensor.hpp, metatensor-torch/src/block.cpp, metatensor-torch/src/labels.cpp, metatensor-torch/src/register.cpp, metatensor-torch/src/tensor.cpp, python/metatensor_core/metatensor/block.py, python/metatensor_core/metatensor/data/array.py, python/metatensor_core/metatensor/labels.py, python/metatensor_core/metatensor/tensor.py, python/metatensor_core/tests/blocks.py, python/metatensor_core/tests/tensor.py, python/metatensor_torch/metatensor/torch/documentation.py, python/metatensor_torch/tests/block.py, python/metatensor_torch/tests/labels.py, python/metatensor_torch/tests/tensor.py
Fix #838 (except for `System`, the corresponding change will happen in https://github.com/metatensor/metatrain).
=> Add `non_blocking` parameter to `to()`

python/metatensor_learn/metatensor/learn/nn/equivariant_transformation.py, python/metatensor_learn/metatensor/learn/nn/layer_norm.py, python/metatensor_learn/metatensor/learn/nn/linear.py, python/metatensor_learn/metatensor/learn/nn/relu.py, python/metatensor_learn/metatensor/learn/nn/silu.py, python/metatensor_learn/metatensor/learn/nn/tanh.py, python/metatensor_operations/metatensor/operations/_split.py
Some links where not working in the docs.
=> Correct syntax for reference to classes in docstrings

docs/src/installation.rst
=> Add the conda packages to the documentation

metatensor-torch/tests/valgrind.supp
Closes #940 which involves a false positive.
=> [MAINT] Add a valgrind suppression

CITATION.cff, README.md, docs/src/cite.rst, docs/src/index.rst
Adding the preprint to the repo. If we agree on a format, I suggest we do the same for metatomic and metatrain.
I am not super happy with the extra docs entry for the citation. But, putting a sentence on the docs landing page feels too much. I am open to other and better ideas.
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/3842022810.zip)
=> Add citation

metatensor-torch/README.md
=> Update links in the metatensor-torch c++ readme

python/metatensor_torch/CMakeLists.txt
Same as https://github.com/metatensor/metatomic/pull/78
[📚 Download documentation for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/3892412712.zip)
[⚙️ Download Python wheels for this pull-request (you can install these with pip)](https://nightly.link/metatensor/metatensor/actions/artifacts/3892429827.zip)
=> Change project type to CXX for `metatensor-torch-python`

docs/src/conf.py, metatensor-torch/CHANGELOG.md
=> Remove all remaining references to ASE

docs/src/core/reference/c/index.rst, docs/src/core/reference/cxx/index.rst, docs/src/core/reference/python/index.rst, metatensor-core/CHANGELOG.md, metatensor-core/Cargo.toml, metatensor-core/tests/cmake-project/CMakeLists.txt, python/metatensor_core/CMakeLists.txt, rust/metatensor-sys/Cargo.toml
=> Release metatensor-core v0.1.17

.codecov.yml, metatensor-core/src/blocks.rs, metatensor-core/src/data.rs, metatensor-core/tests/cpp/blocks.cpp, metatensor-core/tests/cpp/labels.cpp, metatensor-core/tests/cpp/tensor.cpp, rust/metatensor-sys/src/lib.rs, rust/metatensor/Cargo.toml, rust/metatensor/src/block/block_mut.rs, rust/metatensor/src/block/block_ref.rs, rust/metatensor/src/block/owned.rs, rust/metatensor/src/data/array.rs, rust/metatensor/src/labels.rs, rust/metatensor/src/tensor.rs, rust/metatensor/tests/serialization.rs
=> Improve code coverage for Rust code
